#!/bin/bash
# Generate food images in batches of 5
BATCH=5
SLEEP=2

declare -A PROMPTS
PROMPTS["ocvrti-kalamari"]="Crispy fried calamari rings with lemon and tartar sauce professional restaurant photography"
PROMPTS["tartar-iz-govedine-z-zarem"]="Beef tartare with grilled bread and quail egg professional restaurant photography"
PROMPTS["brusketa-s-paradiznikom-in-baziliko"]="Bruschetta with fresh tomatoes basil olive oil on toasted bread professional food photography"
PROMPTS["domaca-pasteta"]="Homemade pate with cornichons and toasted bread professional restaurant photography"
PROMPTS["kremna-gobova-juha"]="Creamy mushroom soup in a bowl with truffle oil drizzle professional restaurant photography"
PROMPTS["rizeva-juha"]="Chicken and rice soup with vegetables in white bowl professional restaurant photography"
PROMPTS["goveja-juha-s-potrebusnino"]="Beef soup with tripe and vegetables in rustic bowl professional restaurant photography"
PROMPTS["cemazeva-juha"]="Wild garlic soup with cream and croutons in white bowl professional restaurant photography"
PROMPTS["minestra"]="Minestrone soup with vegetables and pasta in rustic bowl professional restaurant photography"
PROMPTS["svinjski-zrezek-po-dunajsko"]="Viennese breaded pork schnitzel with lemon potato salad professional restaurant photography"
PROMPTS["svinjski-zrezek-po-ljubljansko"]="Ljubljana style pork schnitzel stuffed with ham and cheese professional restaurant photography"
PROMPTS["telecji-zrezek-v-gobovi-omaki"]="Veal cutlet in creamy mushroom sauce with rice professional restaurant photography"
PROMPTS["puranji-zrezek-po-dunajsko"]="Breaded turkey schnitzel with lemon and roasted potatoes professional restaurant photography"
PROMPTS["goveja-jetra-s-cebulo"]="Beef liver with caramelized onions and mashed potatoes professional restaurant photography"
PROMPTS["goveji-stroganov"]="Beef stroganoff with mushrooms creamy sauce over egg noodles professional restaurant photography"
PROMPTS["piscancji-zrezek-v-smetanovi-omaki"]="Chicken cutlet in creamy sauce with rice professional restaurant photography"
PROMPTS["svinjska-pecenka"]="Roasted pork loin with potatoes and gravy professional restaurant photography"
PROMPTS["svinjska-rebra-z-zara"]="BBQ pork ribs with coleslaw and fries professional restaurant photography"
PROMPTS["medaljoni-iz-govedine"]="Beef medallions with asparagus and red wine sauce professional restaurant photography"
PROMPTS["piscancji-file-v-parmezani"]="Chicken parmesan with mozzarella and tomato sauce over spaghetti professional restaurant photography"
PROMPTS["dunajski-zrezek-s-pomfri"]="Viennese schnitzel with french fries and lemon professional restaurant photography"
PROMPTS["spageti-bolognese"]="Spaghetti bolognese with rich meat sauce and parmesan cheese professional restaurant photography"
PROMPTS["tagliatelle-s-tartufi"]="Tagliatelle pasta with black truffle shavings butter sauce professional restaurant photography"
PROMPTS["penne-s-piscancem-in-curryjem"]="Penne pasta with chicken curry sauce professional restaurant photography"
PROMPTS["ravioli-s-spinaco-in-skuto"]="Ravioli filled with spinach and ricotta in sage butter professional restaurant photography"
PROMPTS["spageti-s-kozicami"]="Spaghetti with prawns in garlic white wine sauce professional restaurant photography"
PROMPTS["fuzi-s-tartufi"]="Istrian fuzi pasta with truffles professional restaurant photography"
PROMPTS["rezanci-z-gobami"]="Homemade noodles with wild mushrooms and cream professional restaurant photography"
PROMPTS["spageti-frutti-di-mare"]="Spaghetti frutti di mare with mixed seafood professional restaurant photography"
PROMPTS["stirje-siri"]="Four cheese pizza with mozzarella gorgonzola gouda parmesan professional restaurant photography"
PROMPTS["gobova-pica"]="Mushroom pizza with wild mushrooms and truffle oil professional restaurant photography"
PROMPTS["diavolo"]="Spicy diavolo pizza with salami and chili peppers professional restaurant photography"
PROMPTS["prosciutto-e-rucola"]="Pizza with prosciutto arugula and parmesan professional restaurant photography"
PROMPTS["tunina-pica"]="Tuna pizza with onions olives and capers professional restaurant photography"
PROMPTS["kraska-pica"]="Kras pizza with prosciutto and olive oil professional restaurant photography"
PROMPTS["havajska-pica"]="Hawaiian pizza with ham and pineapple professional restaurant photography"
PROMPTS["kmecka-pica"]="Rustic pizza with bacon sausage peppers onion professional restaurant photography"
PROMPTS["pica-s-prsutom"]="Pizza with prosciutto crudo fresh mozzarella professional restaurant photography"
PROMPTS["bianca-pica"]="White pizza with mozzarella ricotta and garlic professional restaurant photography"
PROMPTS["bbq-burger"]="BBQ burger with bacon onion rings and BBQ sauce professional restaurant photography"
PROMPTS["double-cheeseburger"]="Double cheeseburger with two beef patties and melted cheese professional restaurant photography"
PROMPTS["chili-burger"]="Chili burger with jalapenos pepper jack cheese and spicy mayo professional restaurant photography"
PROMPTS["burger-z-jajcem-in-slanino"]="Burger with fried egg and crispy bacon professional restaurant photography"
PROMPTS["panna-cotta"]="Panna cotta with berry coulis on white plate professional restaurant photography"
PROMPTS["krofi-s-pomarancno-marmelado"]="Deep fried doughnuts with orange marmalade filling professional restaurant photography"
PROMPTS["ledeni-desert"]="Ice cream dessert with chocolate sauce and berries professional restaurant photography"
PROMPTS["sadna-skleda"]="Fresh fruit bowl with seasonal berries and melon professional restaurant photography"
PROMPTS["domino-kocke"]="Domino cube cake with chocolate and cream layers professional restaurant photography"
PROMPTS["palacinke-z-marmelado"]="Crepes with jam filling powdered sugar professional restaurant photography"
PROMPTS["sladoled-tri-okuse"]="Three scoops of ice cream with different flavors professional restaurant photography"
PROMPTS["njoki"]="Potato gnocchi with tomato sauce and parmesan professional restaurant photography"
PROMPTS["polenta"]="Creamy polenta with butter and parmesan cheese professional restaurant photography"
PROMPTS["mlinci"]="Baked mlinci flatbread pieces with poultry drippings professional restaurant photography"
PROMPTS["krompirjev-pire"]="Creamy mashed potatoes with butter and herbs professional restaurant photography"
PROMPTS["krompirjevi-kroketi"]="Golden fried potato croquettes professional restaurant photography"
PROMPTS["ocvrtki"]="Fried dough pieces traditional Slovenian side dish professional restaurant photography"
PROMPTS["ajdova-kasa"]="Buckwheat porridge with crispy pork bits traditional Slovenian professional restaurant photography"
PROMPTS["bucke-na-zaru"]="Grilled zucchini slices with olive oil and herbs professional restaurant photography"
PROMPTS["zar-zelenjava"]="Grilled mixed vegetables with olive oil professional restaurant photography"
PROMPTS["kuhana-zelenjava"]="Steamed mixed vegetables on white plate professional restaurant photography"
PROMPTS["file-lososa-z-zara"]="Grilled salmon fillet with asparagus and lemon professional restaurant photography"
PROMPTS["file-brancina"]="Grilled sea bass fillet with vegetables professional restaurant photography"
PROMPTS["ocvrti-lignji-s-tartarsko-omako"]="Fried squid rings with tartar sauce and lemon professional restaurant photography"
PROMPTS["hobotnica-z-zara"]="Grilled octopus with potatoes and olive oil professional restaurant photography"
PROMPTS["ribja-pasteta"]="Fish pate with capers and toast professional restaurant photography"
PROMPTS["hrenovke-na-zaru"]="Grilled frankfurter sausages with mustard professional restaurant photography"
PROMPTS["klobase-na-zaru"]="Grilled sausages with sauerkraut and mustard professional restaurant photography"
PROMPTS["piscancji-file-na-zaru"]="Grilled chicken breast with herbs and lemon professional restaurant photography"
PROMPTS["pikantne-klobase"]="Spicy grilled sausages with peppers and onions professional restaurant photography"
PROMPTS["zar-deska-za-dve"]="Grilled meat platter for two with mixed meats and sides professional restaurant photography"
PROMPTS["rizota-s-tartufi"]="Truffle risotto with black truffle shavings professional restaurant photography"
PROMPTS["rizota-z-jurcki"]="Risotto with porcini mushrooms and parmesan professional restaurant photography"
PROMPTS["rizota-s-sparglji"]="Asparagus risotto with parmesan and lemon zest professional restaurant photography"
PROMPTS["rizota-z-buckami-in-feto"]="Zucchini and feta risotto with fresh herbs professional restaurant photography"
PROMPTS["francoski-toast"]="French toast with maple syrup and berries professional restaurant photography"
PROMPTS["jajcni-benedikt"]="Eggs Benedict with hollandaise sauce and ham on English muffin professional restaurant photography"
PROMPTS["sladke-palacinke-z-jagodami"]="Sweet crepes with fresh strawberries and cream professional restaurant photography"
PROMPTS["granola-z-jogurtom"]="Granola with yogurt and fresh berries breakfast bowl professional restaurant photography"
PROMPTS["kava-in-krof"]="Coffee and traditional Slovenian doughnut breakfast professional restaurant photography"
PROMPTS["piscancji-nugeti-s-pomfri"]="Chicken nuggets with french fries kids meal professional restaurant photography"
PROMPTS["mini-burger-s-pomfri"]="Mini burger with french fries kids meal professional restaurant photography"
PROMPTS["krompircek-s-piscancem"]="Chicken pieces with potato wedges kids meal professional restaurant photography"
PROMPTS["sladoled-za-otroke"]="Kids ice cream with sprinkles and waffle cone professional restaurant photography"
PROMPTS["toast-s-sirom-na-zaru"]="Grilled cheese sandwich with melted cheese professional restaurant photography"
PROMPTS["panini-s-prsutom-in-mocarelo"]="Panini with prosciutto and mozzarella professional restaurant photography"
PROMPTS["club-sendvic-s-piscancem"]="Club sandwich with chicken bacon lettuce tomato professional restaurant photography"
PROMPTS["wrap-s-piscancem-in-zelenjavo"]="Chicken wrap with fresh vegetables professional restaurant photography"
PROMPTS["bograc"]="Prekmurski bograc traditional Slovenian stew in cast iron pot professional restaurant photography"
PROMPTS["segedin"]="Segedin stew with pork and sauerkraut professional restaurant photography"
PROMPTS["krvavica-s-kislim-zeljem"]="Blood sausage with sauerkraut traditional Slovenian dish professional restaurant photography"
PROMPTS["idrijski-zlikrofi"]="Idrija zlikrofi traditional Slovenian dumplings with breadcrumbs professional restaurant photography"
PROMPTS["prekmurska-gibanica"]="Prekmurska gibanica layered cake poppy seeds walnuts apples cottage cheese professional restaurant photography"
PROMPTS["kmecki-kroznik"]="Traditional Slovenian farmers plate with mixed meats and sides professional restaurant photography"
PROMPTS["mlinci-s-puranom"]="Baked mlinci with roast turkey traditional Slovenian professional restaurant photography"
PROMPTS["obara-z-ajdovo-kaso"]="Traditional Slovenian stew with buckwheat porridge professional restaurant photography"
PROMPTS["domace-pecenice-s-kislim-zeljem"]="Homemade sausages with sauerkraut traditional Slovenian professional restaurant photography"
PROMPTS["potica"]="Traditional Slovenian potica walnut roll cake sliced professional restaurant photography"

count=0
total=0
for slug in "${!PROMPTS[@]}"; do
  if [ ! -f "./public/menu-images/${slug}.png" ]; then
    total=$((total + 1))
  fi
done

for slug in "${!PROMPTS[@]}"; do
  if [ ! -f "./public/menu-images/${slug}.png" ]; then
    count=$((count + 1))
    echo "[$count/$total] $slug"
    z-ai-generate -p "${PROMPTS[$slug]}, top-down view, restaurant menu photo, warm lighting, clean background" -o "./public/menu-images/${slug}.png" -s 1024x1024 2>/dev/null && echo "  OK" || echo "  FAIL"
    sleep 1
  fi
done
echo "Done! Generated $count images"
