#!/bin/bash
# Generate images for all new food items

ITEMS=(
  "goveji-tatar:Beef tartare on a white plate with capers onions and toast professional restaurant photography"
  "caprese:Fresh caprese salad with mozzarella tomatoes basil and olive oil on rustic plate professional food photography"
  "tartar-iz-lososa:Salmon tartare with avocado sesame and microgreens on dark plate professional restaurant photography"
  "mesna-deska-s-sirom:Charcuterie board with cured meats cheeses olives and dried fruits professional restaurant photography"
  "ocvrti-kalamari:Crispy fried calamari rings with lemon and tartar sauce professional restaurant photography"
  "tartar-iz-govedine-z-zarem:Beef tartare with grilled bread and quail egg professional restaurant photography"
  "brusketa-s-paradiznikom-in-baziliko:Bruschetta with fresh tomatoes basil and olive oil on toasted bread professional food photography"
  "domaca-pasteta:Homemade pate with cornichons and toasted bread professional restaurant photography"
  "kremna-gobova-juha:Creamy mushroom soup in a bowl with truffle oil drizzle professional restaurant photography"
  "rizeva-juha:Chicken and rice soup with vegetables in white bowl professional restaurant photography"
  "goveja-juha-s-potrebusnino:Beef soup with tripe and vegetables in rustic bowl professional restaurant photography"
  "cemazeva-juha:Wild garlic soup with cream and croutons in white bowl professional restaurant photography"
  "minestra:Minestrone soup with vegetables and pasta in rustic bowl professional restaurant photography"
  "svinjski-zrezek-po-dunajsko:Viennese style breaded pork schnitzel with lemon and potato salad professional restaurant photography"
  "svinjski-zrezek-po-ljubljansko:Ljubljana style pork schnitzel stuffed with ham and cheese professional restaurant photography"
  "telecji-zrezek-v-gobovi-omaki:Veal cutlet in creamy mushroom sauce with rice professional restaurant photography"
  "puranji-zrezek-po-dunajsko:Breaded turkey schnitzel with lemon and roasted potatoes professional restaurant photography"
  "goveja-jetra-s-cebulo:Beef liver with caramelized onions and mashed potatoes professional restaurant photography"
  "goveji-stroganov:Beef stroganoff with mushrooms in creamy sauce over egg noodles professional restaurant photography"
  "piscancji-zrezek-v-smetanovi-omaki:Chicken cutlet in creamy sauce with rice professional restaurant photography"
  "svinjska-pecenka:Roasted pork loin with potatoes and gravy professional restaurant photography"
  "svinjska-rebra-z-zara:BBQ pork ribs with coleslaw and fries professional restaurant photography"
  "medaljoni-iz-govedine:Beef medallions with asparagus and red wine sauce professional restaurant photography"
  "piscancji-file-v-parmezani:Chicken parmesan with mozzarella and tomato sauce over spaghetti professional restaurant photography"
  "dunajski-zrezek-s-pomfri:Viennese schnitzel with french fries and lemon professional restaurant photography"
  "spageti-bolognese:Spaghetti bolognese with rich meat sauce and parmesan cheese professional restaurant photography"
  "tagliatelle-s-tartufi:Tagliatelle pasta with black truffle shavings and butter sauce professional restaurant photography"
  "penne-s-piscancem-in-curryjem:Penne pasta with chicken curry sauce professional restaurant photography"
  "ravioli-s-spinaco-in-skuto:Ravioli filled with spinach and ricotta in sage butter professional restaurant photography"
  "spageti-s-kozicami:Spaghetti with prawns in garlic white wine sauce professional restaurant photography"
  "fuzi-s-tartufi:Istrian fuži pasta with truffles professional restaurant photography"
  "rezanci-z-gobami:Homemade noodles with wild mushrooms and cream professional restaurant photography"
  "spageti-frutti-di-mare:Spaghetti frutti di mare with mixed seafood professional restaurant photography"
  "stirje-siri:Four cheese pizza with mozzarella gorgonzola gouda and parmesan professional restaurant photography"
  "gobova-pica:Mushroom pizza with mixed wild mushrooms and truffle oil professional restaurant photography"
  "diavolo:Spicy diavolo pizza with salami and chili peppers professional restaurant photography"
  "prosciutto-e-rucola:Pizza with prosciutto arugula and parmesan professional restaurant photography"
  "tunina-pica:Tuna pizza with onions olives and capers professional restaurant photography"
  "kraska-pica:Kras pizza with prosciutto and olive oil professional restaurant photography"
  "havajska-pica:Hawaiian pizza with ham and pineapple professional restaurant photography"
  "kmecka-pica:Rustic pizza with bacon sausage peppers and onion professional restaurant photography"
  "pica-s-prsutom:Pizza with prosciutto crudo and fresh mozzarella professional restaurant photography"
  "bianca-pica:White pizza with mozzarella ricotta and garlic professional restaurant photography"
  "bbq-burger:BBQ burger with bacon onion rings and BBQ sauce professional restaurant photography"
  "double-cheeseburger:Double cheeseburger with two beef patties and melted cheese professional restaurant photography"
  "chili-burger:Chili burger with jalapenos pepper jack cheese and spicy mayo professional restaurant photography"
  "burger-z-jajcem-in-slanino:Burger with fried egg and crispy bacon professional restaurant photography"
  "panna-cotta:Panna cotta with berry coulis on white plate professional restaurant photography"
  "krofi-s-pomarancno-marmelado:Deep fried doughnuts with orange marmalade filling professional restaurant photography"
  "ledeni-desert:Ice cream dessert with chocolate sauce and berries professional restaurant photography"
  "sadna-skleda:Fresh fruit bowl with seasonal berries and melon professional restaurant photography"
  "domino-kocke:Domino cube cake with chocolate and cream layers professional restaurant photography"
  "palacinke-z-marmelado:Crepes with jam filling powdered sugar professional restaurant photography"
  "sladoled-tri-okuse:Three scoops of ice cream with different flavors professional restaurant photography"
  "njoki:Potato gnocchi with tomato sauce and parmesan professional restaurant photography"
  "polenta:Creamy polenta with butter and parmesan cheese professional restaurant photography"
  "mlinci:Baked mlinci flatbread pieces with poultry drippings professional restaurant photography"
  "krompirjev-pire:Creamy mashed potatoes with butter and herbs professional restaurant photography"
  "krompirjevi-kroketi:Golden fried potato croquettes professional restaurant photography"
  "ocvrtki:Fried dough pieces traditional Slovenian side dish professional restaurant photography"
  "ajdova-kasa:Buckwheat porridge with crispy pork bits traditional Slovenian professional restaurant photography"
  "bucke-na-zaru:Grilled zucchini slices with olive oil and herbs professional restaurant photography"
  "zar-zelenjava:Grilled mixed vegetables with olive oil professional restaurant photography"
  "kuhana-zelenjava:Steamed mixed vegetables on white plate professional restaurant photography"
  "file-lososa-z-zara:Grilled salmon fillet with asparagus and lemon professional restaurant photography"
  "file-brancina:Grilled sea bass fillet with vegetables professional restaurant photography"
  "ocvrti-lignji-s-tartarsko-omako:Fried squid rings with tartar sauce and lemon professional restaurant photography"
  "hobotnica-z-zara:Grilled octopus with potatoes and olive oil professional restaurant photography"
  "ribja-pasteta:Fish pate with capers and toast professional restaurant photography"
  "hrenovke-na-zaru:Grilled frankfurter sausages with mustard professional restaurant photography"
  "klobase-na-zaru:Grilled sausages with sauerkraut and mustard professional restaurant photography"
  "piscancji-file-na-zaru:Grilled chicken breast with herbs and lemon professional restaurant photography"
  "pikantne-klobase:Spicy grilled sausages with peppers and onions professional restaurant photography"
  "zar-deska-za-dve:Grilled meat platter for two with mixed meats and sides professional restaurant photography"
  "rizota-s-tartufi:Truffle risotto with black truffle shavings professional restaurant photography"
  "rizota-z-jurcki:Risotto with porcini mushrooms and parmesan professional restaurant photography"
  "rizota-s-sparglji:Asparagus risotto with parmesan and lemon zest professional restaurant photography"
  "rizota-z-buckami-in-feto:Zucchini and feta risotto with fresh herbs professional restaurant photography"
  "francoski-toast:French toast with maple syrup and berries professional restaurant photography"
  "jajcni-benedikt:Eggs Benedict with hollandaise sauce and ham on English muffin professional restaurant photography"
  "sladke-palacinke-z-jagodami:Sweet crepes with fresh strawberries and cream professional restaurant photography"
  "granola-z-jogurtom:Granola with yogurt and fresh berries breakfast bowl professional restaurant photography"
  "kava-in-krof:Coffee and traditional Slovenian doughnut breakfast professional restaurant photography"
  "piscancji-nugeti-s-pomfri:Chicken nuggets with french fries kids meal professional restaurant photography"
  "mini-burger-s-pomfri:Mini burger with french fries kids meal professional restaurant photography"
  "krompircek-s-piscancem:Chicken pieces with potato wedges kids meal professional restaurant photography"
  "sladoled-za-otroke:Kids ice cream with sprinkles and waffle cone professional restaurant photography"
  "toast-s-sirom-na-zaru:Grilled cheese sandwich with melted cheese professional restaurant photography"
  "panini-s-prsutom-in-mocarelo:Panini with prosciutto and mozzarella professional restaurant photography"
  "club-sendvic-s-piscancem:Club sandwich with chicken bacon lettuce and tomato professional restaurant photography"
  "wrap-s-piscancem-in-zelenjavo:Chicken wrap with fresh vegetables professional restaurant photography"
  "bograc:Prekmurski bograc traditional Slovenian stew in cast iron pot professional restaurant photography"
  "segedin:Segedin stew with pork and sauerkraut in pot professional restaurant photography"
  "krvavica-s-kislim-zeljem:Blood sausage with sauerkraut traditional Slovenian dish professional restaurant photography"
  "idrijski-zlikrofi:Idrija žlikrofi traditional Slovenian dumplings with breadcrumbs professional restaurant photography"
  "prekmurska-gibanica:Prekmurska gibanica layered cake with poppy seeds walnuts apples and cottage cheese professional restaurant photography"
  "kmecki-kroznik:Traditional Slovenian farmers plate with mixed meats and sides professional restaurant photography"
  "mlinci-s-puranom:Baked mlinci with roast turkey traditional Slovenian professional restaurant photography"
  "obara-z-ajdovo-kaso:Traditional Slovenian stew with buckwheat porridge professional restaurant photography"
  "domace-pecenice-s-kislim-zeljem:Homemade sausages with sauerkraut traditional Slovenian professional restaurant photography"
  "potica:Traditional Slovenian potica walnut roll cake sliced professional restaurant photography"
)

TOTAL=${#ITEMS[@]}
COUNT=0
FAIL=0

for ITEM in "${ITEMS[@]}"; do
  SLUG="${ITEM%%:*}"
  PROMPT="${ITEM#*:}"
  OUTPUT="./public/menu-images/${SLUG}.png"
  
  COUNT=$((COUNT + 1))
  echo "[$COUNT/$TOTAL] Generating: $SLUG"
  
  if z-ai-generate -p "$PROMPT, top-down view, restaurant menu photo, warm lighting, clean background, 4k food photography" -o "$OUTPUT" -s 1024x1024 2>/dev/null; then
    echo "  ✓ OK"
  else
    echo "  ✗ FAILED"
    FAIL=$((FAIL + 1))
  fi
  
  # Small delay to avoid rate limiting
  sleep 1
done

echo ""
echo "Done! Generated: $((COUNT - FAIL))/$COUNT, Failed: $FAIL"
