/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is automatically generated by Sentry wizard.
// Instrumentation hook — loads Sentry config before the app starts.
// Next.js 16 auto-calls register() on startup.

import * as Sentry from '@sentry/nextjs'

export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    await import('./sentry.server.config')
  }
  if (process.env.NEXT_RUNTIME === 'edge') {
    await import('./sentry.edge.config')
  }
}

// Capture errors from Next.js 15+ Request Handler (App Router)
export const onRequestError = Sentry.captureRequestError
