// Recepti za palačinke, otroške jedi in malice

import type { InvItem, RecipeEntry } from '../../types'

export function buildPalacinkeOtrociMaliceRecipes(inv: Record<string, InvItem>): RecipeEntry[] {
  const {
    invMokaPalacinke, invJajca, invJagodniPire, invLinoLada, invBelaCokolada,
    invPlazmaPiskot, invMandlji, invKokosovaMoka, invRaffaello, invKakavZaPalačinke,
    invNutella, invKinderBueno, invArasidi, invSnickers, invFerreroRocher, invMandM,
    invGauda, invPommesFrites, invSvinjskiZrezek, invPuramjiFile, invTestoZaPica,
    invPelati, invMozzarella, invMoka, invSolata, invRebra, invKrompir,
    invPiscancjiFile, invBBQOmaka, invSvinjskaPecenko, invOslic, invSpageti,
    invMletnoMeso, invParadiznik, invSampinjoni, invGovedinaBograch, invCebula,
    invPaprika, invGovedinaZaGolaz,
  } = inv

  return [
    // --- PALAČINKE ---
    { menuItemName: 'Hišna sladica', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka' },
    { menuItemName: 'Hišna sladica', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Hišna sladica', ingredientId: invJagodniPire.id, quantityPerServing: 0.05, unit: 'kg', notes: 'jagodni pire' },
    { menuItemName: 'Hišna sladica', ingredientId: invLinoLada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Lino Lada' },
    { menuItemName: 'Hišna sladica', ingredientId: invBelaCokolada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'bela čokolada' },
    { menuItemName: 'Hišna sladica', ingredientId: invPlazmaPiskot.id, quantityPerServing: 0.02, unit: 'kg', notes: 'Plazma biskvit' },
    { menuItemName: 'Raffaello', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka' },
    { menuItemName: 'Raffaello', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Raffaello', ingredientId: invBelaCokolada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'bela čokolada' },
    { menuItemName: 'Raffaello', ingredientId: invLinoLada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Lino Lada' },
    { menuItemName: 'Raffaello', ingredientId: invMandlji.id, quantityPerServing: 0.02, unit: 'kg', notes: 'mandlji' },
    { menuItemName: 'Raffaello', ingredientId: invKokosovaMoka.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kokosova moka' },
    { menuItemName: 'Raffaello', ingredientId: invRaffaello.id, quantityPerServing: 1, unit: 'kos', notes: 'Raffaello kroglica' },
    { menuItemName: 'Kinder Bueno', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Kinder Bueno', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Kinder Bueno', ingredientId: invKakavZaPalačinke.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kakav' },
    { menuItemName: 'Kinder Bueno', ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čokoladno-lešnikova krema' },
    { menuItemName: 'Kinder Bueno', ingredientId: invKinderBueno.id, quantityPerServing: 1, unit: 'kos', notes: 'Kinder Bueno' },
    { menuItemName: 'Snickers', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Snickers', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Snickers', ingredientId: invKakavZaPalačinke.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kakav' },
    { menuItemName: 'Snickers', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },
    { menuItemName: 'Snickers', ingredientId: invSnickers.id, quantityPerServing: 1, unit: 'kos', notes: 'Snickers' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čokoladno-lešnikova krema' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invMandlji.id, quantityPerServing: 0.02, unit: 'kg', notes: 'lešniki' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invFerreroRocher.id, quantityPerServing: 1, unit: 'kos', notes: 'Ferrero Rocher' },
    { menuItemName: "M&M's", ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: "M&M's", ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: "M&M's", ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Nutella' },
    { menuItemName: "M&M's", ingredientId: invMandM.id, quantityPerServing: 0.02, unit: 'kg', notes: "M&M's" },

    // --- OTROŠKE JEDI ---
    { menuItemName: 'Krožnik Miškolin', ingredientId: invGauda.id, quantityPerServing: 0.15, unit: 'kg', notes: 'ocvrti sir' },
    { menuItemName: 'Krožnik Miškolin', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Krožnik Korenjak', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.15, unit: 'kg', notes: 'dunajski zrezek' },
    { menuItemName: 'Krožnik Korenjak', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Otroški pohančki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran/piščanec' },
    { menuItemName: 'Otroški pohančki', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Pizza Malček', ingredientId: invTestoZaPica.id, quantityPerServing: 0.5, unit: 'kg', notes: 'manjše testo' },
    { menuItemName: 'Pizza Malček', ingredientId: invPelati.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Pizza Malček', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'mozzarella' },

    // --- MALICE (Dnevno kosilo) ---
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g zrezek' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g zrezek' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invRebra.id, quantityPerServing: 0.30, unit: 'kg', notes: '300g rebra' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invKrompir.id, quantityPerServing: 0.25, unit: 'kg', notes: 'pražen krompir' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.25, unit: 'kg', notes: 'piščančje perutničke' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invBBQOmaka.id, quantityPerServing: 0.05, unit: 'L', notes: 'BBQ omaka' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invSvinjskaPecenko.id, quantityPerServing: 0.30, unit: 'kg', notes: '300g pečenka' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invKrompir.id, quantityPerServing: 0.25, unit: 'kg', notes: 'pražen krompir' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invOslic.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g oslič' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invKrompir.id, quantityPerServing: 0.20, unit: 'kg', notes: 'krompirjeva solata' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invOslic.id, quantityPerServing: 0.15, unit: 'kg', notes: '150g oslič' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Ocvrti sir', ingredientId: invGauda.id, quantityPerServing: 0.15, unit: 'kg', notes: 'ocvrti sir' },
    { menuItemName: 'Malica - Ocvrti sir', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invSpageti.id, quantityPerServing: 0.15, unit: 'kg', notes: 'špageti' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invMletnoMeso.id, quantityPerServing: 0.10, unit: 'kg', notes: 'bolognese omaka' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invParadiznik.id, quantityPerServing: 0.05, unit: 'kg', notes: 'paradižnikova omaka' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invMletnoMeso.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mesni sir' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invSampinjoni.id, quantityPerServing: 0.03, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Malica - Bograč', ingredientId: invGovedinaBograch.id, quantityPerServing: 0.15, unit: 'kg', notes: 'govedina' },
    { menuItemName: 'Malica - Bograč', ingredientId: invParadiznik.id, quantityPerServing: 0.05, unit: 'kg', notes: 'paradižnik' },
    { menuItemName: 'Malica - Bograč', ingredientId: invCebula.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Malica - Bograč', ingredientId: invPaprika.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paprika' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invGovedinaZaGolaz.id, quantityPerServing: 0.15, unit: 'kg', notes: 'govedina' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invCebula.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invParadiznik.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paradižnikova omaka' },
  ]
}
