import { CategoryRef, MenuItemSeed } from './types'

// =====================================================================
// PIJAČA - Vina (penine, bela, rosé, rdeča, tuja, likerska)
// =====================================================================

export function getDrinksWine(
  cats: Record<string, CategoryRef>
): MenuItemSeed[] {
  return [
    // --- PENINE IN ŠAMPANJCI ---
    { name: 'No.1 Brut', description: 'Chardonnay, rumeni plavec | Istenič, Bizeljsko-Sremič, Posavje | Zelo suho', price: 40.00, image: '/menu-images/penine/no1-brut.png', categoryId: cats.penine.id, sortOrder: 0, modifierGroupIds: [] },
    { name: 'Domaine Slapšak Brut Reserve', description: 'Žametna črnina, modri pinot | Domaine Slapšak, Dolenjska, Posavje | Zelo suho', price: 45.00, image: '/menu-images/penine/slapsak-brut-reserve.png', categoryId: cats.penine.id, sortOrder: 1, modifierGroupIds: [] },
    { name: 'Domaine Slapšak Brut Rosé', description: '100% žametna črnina | Domaine Slapšak, Dolenjska, Posavje | Zelo suho', price: 45.00, image: '/menu-images/penine/slapsak-brut-rose.png', categoryId: cats.penine.id, sortOrder: 2, modifierGroupIds: [] },
    { name: 'Penina Gourmet Rosé', description: '100% modri pinot | Klet Istenič, Bizeljsko-Sremič, Posavje | Suho', price: 40.00, image: '/menu-images/penine/gourmet-rose.png', categoryId: cats.penine.id, sortOrder: 3, modifierGroupIds: [] },
    { name: 'Zlata Radgonska Penina Brut Selection', description: 'Chardonnay | Radgonske gorice, Gornja radgona, Štajerska, Podravje | Zelo suho', price: 36.00, image: '/menu-images/penine/zlata-radgonska.png', categoryId: cats.penine.id, sortOrder: 4, modifierGroupIds: [] },
    { name: 'Maria Brut 2020', description: 'Chardonnay, rumeni plavec, kraljevina | Vinarstvo Kerin, Dolenjska, Posavje | Zelo suho', price: 35.00, image: '/menu-images/penine/maria-brut.png', categoryId: cats.penine.id, sortOrder: 5, modifierGroupIds: [] },
    { name: 'Penina Boemme Rumeni Muškat', description: 'Hiša vin Emino, Štajerska Slovenija | Polsuho', price: 35.00, image: '/menu-images/penine/boemme-rumeni-muskat.png', categoryId: cats.penine.id, sortOrder: 6, modifierGroupIds: [] },
    { name: 'Bjana Brut', description: 'Chardonnay, modri pinot | Bjana, Miran Sirk, Goriška Brda, Primorska | Zelo suho', price: 55.00, image: '/menu-images/penine/bjana-brut.png', categoryId: cats.penine.id, sortOrder: 7, modifierGroupIds: [] },
    { name: 'Mufi Pet Nat Brut Nature 2023', description: 'Rumeni muškat, rumeni plavec | Ekološko, Keltis, Bizeljsko-Sremič, Posavje | Izredno suho', price: 35.00, image: '/menu-images/penine/mufi-pet-nat.png', categoryId: cats.penine.id, sortOrder: 8, modifierGroupIds: [] },
    { name: 'Champagne Louis Roederer Collection 244 Brut', description: 'Chardonnay, pinot noir, pinot meunier | Louis Roederer, Reims, Francija | Zelo suho', price: 102.00, image: '/menu-images/penine/louis-roederer.png', categoryId: cats.penine.id, sortOrder: 9, modifierGroupIds: [] },
    { name: 'Champagne Pol Roger Brut Reserve', description: 'Chardonnay, modri pinot, pinot meunier | Epernay, Francija | Zelo suho', price: 102.00, image: '/menu-images/penine/pol-roger.png', categoryId: cats.penine.id, sortOrder: 10, modifierGroupIds: [] },
    { name: 'Moët & Chandon Imperial Brut', description: 'Pinot noir, pinot meunier, chardonnay | Moët&Chandon, Epernay, Francija | Zelo suho', price: 95.00, image: '/menu-images/penine/moet-chandon.png', categoryId: cats.penine.id, sortOrder: 11, modifierGroupIds: [] },
    { name: 'Dom Pérignon Brut 2013', description: 'Chardonnay, modri pinot | Epernay, Francija | Zelo suho', price: 390.00, image: '/menu-images/penine/dom-perignon.png', categoryId: cats.penine.id, sortOrder: 12, modifierGroupIds: [] },

    // --- BELA VINA ---
    { name: 'Cuvee Emino 2022 (kozarec)', description: 'Laški rizling, chardonnay, sauvignon | Hiša vin Emino, Šmarje pri Jelšah, Štajerska | Suho | 0.10L', price: 3.00, image: '/menu-images/bela-vina/cuvee-emino-kozarec.png', categoryId: cats.belaVina.id, sortOrder: 0, modifierGroupIds: [] },
    { name: 'Cuvee Emino 2022 (steklenica)', description: 'Laški rizling, chardonnay, sauvignon | Hiša vin Emino, Šmarje pri Jelšah, Štajerska | Suho | 0.75L', price: 21.00, image: '/menu-images/bela-vina/cuvee-emino-steklenica.png', categoryId: cats.belaVina.id, sortOrder: 1, modifierGroupIds: [] },
    { name: 'Chardonnay Verus 2023', description: 'Verus, Štajerska Slovenija, Podravje | Suho | 0.75L', price: 35.00, image: '/menu-images/bela-vina/chardonnay-verus.png', categoryId: cats.belaVina.id, sortOrder: 2, modifierGroupIds: [] },
    { name: 'Sauvignon Blanc Cru Veliki Vrh 2023', description: 'Familija Brodnjak, Haloze, Štajerska Slovenija, Podravje | Suho | 0.75L', price: 42.00, image: '/menu-images/bela-vina/sauvignon-blanc-cru.png', categoryId: cats.belaVina.id, sortOrder: 3, modifierGroupIds: [] },
    { name: 'Laški Rizling 2021', description: 'Janez Colnar, Dolenjska | Suho | 0.75L', price: 35.00, image: '/menu-images/bela-vina/laski-rizling.png', categoryId: cats.belaVina.id, sortOrder: 4, modifierGroupIds: [] },
    { name: 'Traminec 2023', description: 'Butična klet Keltis, Bizeljsko-Sremič, Posavje | Suho | 0.75L', price: 39.00, image: '/menu-images/bela-vina/traminec.png', categoryId: cats.belaVina.id, sortOrder: 5, modifierGroupIds: [] },
    { name: 'Rebula 2022', description: 'Borut Blažič, Goriška Brda, Primorska | Suho | 0.75L', price: 35.00, image: '/menu-images/bela-vina/rebula.png', categoryId: cats.belaVina.id, sortOrder: 6, modifierGroupIds: [] },
    { name: 'Chardonnay Dular 2022', description: 'Ekološko vino | Klet Dular, Bizeljsko-Sremič, Posavje | Suho | 0.75L', price: 50.00, image: '/menu-images/bela-vina/chardonnay-dular.png', categoryId: cats.belaVina.id, sortOrder: 7, modifierGroupIds: [] },
    { name: 'Chardonnay Domaine Vicomte de Noue 2020', description: 'Marinčič Tejca, Vedrignano II Cru, Goriška Brda, Primorska | Suho | 0.75L', price: 120.00, image: '/menu-images/bela-vina/chardonnay-vicomte.png', categoryId: cats.belaVina.id, sortOrder: 8, modifierGroupIds: [] },
    { name: 'Šipon Verus 2022', description: 'Verus, Štajerska Slovenija, Podravje | Suho | 0.75L', price: 35.00, image: '/menu-images/bela-vina/sipon-verus.png', categoryId: cats.belaVina.id, sortOrder: 9, modifierGroupIds: [] },
    { name: 'Sivi Pinot Jamertal 2021', description: 'Valdhuber, Štajerska Slovenija, Podravje | Suho | 0.75L', price: 38.00, image: '/menu-images/bela-vina/sivi-pinot-jamertal.png', categoryId: cats.belaVina.id, sortOrder: 10, modifierGroupIds: [] },
    { name: 'Renski Rizling Stare Trte 2015', description: 'Dveri-Pax, Štajerska Slovenija, Podravje | Suho | 0.75L', price: 39.00, image: '/menu-images/bela-vina/renski-rizling-stare.png', categoryId: cats.belaVina.id, sortOrder: 11, modifierGroupIds: [] },
    { name: 'Renski Rizling Keltis 2021', description: 'Ekološko vino | Keltis, Bizeljsko-Sremič, Posavje | Suho | 0.75L', price: 44.00, image: '/menu-images/bela-vina/renski-rizling-keltis.png', categoryId: cats.belaVina.id, sortOrder: 12, modifierGroupIds: [] },
    { name: 'Alter 2021', description: 'Ekološko vino | Renski rizling, laški rizling, sivi pinot | Kmetija Šumenjak, Štajerska, Podravje | Suho | 0.75L', price: 42.00, image: '/menu-images/bela-vina/alter.png', categoryId: cats.belaVina.id, sortOrder: 13, modifierGroupIds: [] },
    { name: 'Malvazija Malval Movia 2023', description: 'Movia, Goriška Brda, Primorska | Suho | 0.75L', price: 36.00, image: '/menu-images/bela-vina/malvazija-movia.png', categoryId: cats.belaVina.id, sortOrder: 14, modifierGroupIds: [] },
    { name: 'Rebula Cru Selection 2021', description: 'Marjan Simčič, Goriška Brda, Primorska | Suho | 0.75L', price: 55.00, image: '/menu-images/bela-vina/rebula-cru.png', categoryId: cats.belaVina.id, sortOrder: 15, modifierGroupIds: [] },
    { name: 'Burja Bela 2022', description: 'Ekološko Demeter | Malvazija, laški rizling, rebula | Posestvo Burja, Vipavska dolina, Primorska | Suho | 0.75L', price: 40.00, image: '/menu-images/bela-vina/burja-bela.png', categoryId: cats.belaVina.id, sortOrder: 16, modifierGroupIds: [] },
    { name: 'Angel Belo Grande Cuvee 2021', description: 'Ekološko vino | Chardonnay, sauvignon, pinela, laški rizling, sivi pinot | Klet Batič, Vipavska dolina, Primorska | Suho | 0.75L', price: 66.00, image: '/menu-images/bela-vina/angel-belo-2021.png', categoryId: cats.belaVina.id, sortOrder: 17, modifierGroupIds: [] },
    { name: 'Angel Belo Grande Cuvee 2019', description: 'Ekološko vino | Chardonnay, sauvignon, pinela, laški rizling, sivi pinot | Klet Batič, Vipavska dolina, Primorska | Suho | 3.00L', price: 280.00, image: '/menu-images/bela-vina/angel-belo-2019.png', categoryId: cats.belaVina.id, sortOrder: 18, modifierGroupIds: [] },
    { name: 'Rumeni Muškat 2023 (kozarec)', description: 'Klet Dular, Bizeljsko-Sremič, Posavje | Polsladko | 0.10L', price: 4.50, image: '/menu-images/bela-vina/rumeni-muskat-kozarec.png', categoryId: cats.belaVina.id, sortOrder: 19, modifierGroupIds: [] },
    { name: 'Rumeni Muškat 2023 (steklenica)', description: 'Klet Dular, Bizeljsko-Sremič, Posavje | Polsladko | 0.75L', price: 30.00, image: '/menu-images/bela-vina/rumeni-muskat-steklenica.png', categoryId: cats.belaVina.id, sortOrder: 20, modifierGroupIds: [] },
    { name: 'Rumeni Muškat Pozna Trgatev 2019 (kozarec)', description: 'Klet Prus, Metlika, Bela Krajina, Posavje | Sladko | 0.10L', price: 6.50, image: '/menu-images/bela-vina/rumeni-muskat-pozna-kozarec.png', categoryId: cats.belaVina.id, sortOrder: 21, modifierGroupIds: [] },
    { name: 'Rumeni Muškat Pozna Trgatev 2019 (steklenica)', description: 'Klet Prus, Metlika, Bela Krajina, Posavje | Sladko | 0.75L', price: 38.00, image: '/menu-images/bela-vina/rumeni-muskat-pozna-steklenica.png', categoryId: cats.belaVina.id, sortOrder: 22, modifierGroupIds: [] },
    { name: 'Bela Frankinja 2023 (kozarec)', description: 'Klet Dular, Bizeljsko-Sremič, Posavje | Polsladko | 0.10L', price: 5.00, image: '/menu-images/bela-vina/bela-frankinja-kozarec.png', categoryId: cats.belaVina.id, sortOrder: 23, modifierGroupIds: [] },
    { name: 'Bela Frankinja 2023 (steklenica)', description: 'Klet Dular, Bizeljsko-Sremič, Posavje | Polsladko | 0.75L', price: 35.00, image: '/menu-images/bela-vina/bela-frankinja-steklenica.png', categoryId: cats.belaVina.id, sortOrder: 24, modifierGroupIds: [] },

    // --- ROSÉ VINO ---
    { name: 'Rosé Batič 2024', description: 'Cabernet sauvignon | Batič, Vipavska dolina, Primorska | Polsuho | 0.75L', price: 43.00, image: '/menu-images/rose-vino/rose-batic.png', categoryId: cats.roseVino.id, sortOrder: 0, modifierGroupIds: [] },
    { name: 'Rosé Verstovšek Estate 2024 (kozarec)', description: 'Modra frankinja | Verstovšek Estate, Bizeljsko-Sremič, Posavje | Suho | 0.10L', price: 4.80, image: '/menu-images/rose-vino/rose-verstovsek-kozarec.png', categoryId: cats.roseVino.id, sortOrder: 1, modifierGroupIds: [] },
    { name: 'Rosé Verstovšek Estate 2024 (steklenica)', description: 'Modra frankinja | Verstovšek Estate, Bizeljsko-Sremič, Posavje | Suho | 0.75L', price: 35.00, image: '/menu-images/rose-vino/rose-verstovsek-steklenica.png', categoryId: cats.roseVino.id, sortOrder: 2, modifierGroupIds: [] },

    // --- RDEČA VINA ---
    { name: 'Modra Frankinja Emino 2023 (kozarec)', description: 'Hiša vin Emino, Šmarje pri Jelšah, Štajerska | Suho | 0.10L', price: 3.00, image: '/menu-images/rdeca-vina/modra-frankinja-emino-kozarec.png', categoryId: cats.rdecaVina.id, sortOrder: 0, modifierGroupIds: [] },
    { name: 'Modra Frankinja Emino 2023 (steklenica)', description: 'Hiša vin Emino, Šmarje pri Jelšah, Štajerska | Suho | 0.75L', price: 21.00, image: '/menu-images/rdeca-vina/modra-frankinja-emino-steklenica.png', categoryId: cats.rdecaVina.id, sortOrder: 1, modifierGroupIds: [] },
    { name: 'Modra Frankinja Dular 2023', description: 'Klet Dular, Bizeljsko-Sremič, Posavje | Suho | 0.75L', price: 30.00, image: '/menu-images/rdeca-vina/modra-frankinja-dular.png', categoryId: cats.rdecaVina.id, sortOrder: 2, modifierGroupIds: [] },
    { name: 'Modra Frankinja Luna 2021', description: 'Kmetija Kobal, Bizeljsko-Sremič, Posavje | Suho | 0.75L', price: 68.00, image: '/menu-images/rdeca-vina/modra-frankinja-luna.png', categoryId: cats.rdecaVina.id, sortOrder: 3, modifierGroupIds: [] },
    { name: 'Modri Pinot Verus 2019', description: 'Verus, Ormož, Štajerska Slovenija, Podravje | Suho | 0.75L', price: 38.00, image: '/menu-images/rdeca-vina/modri-pinot-verus.png', categoryId: cats.rdecaVina.id, sortOrder: 4, modifierGroupIds: [] },
    { name: 'Modri Pinot Opoka 2020', description: 'Marjan Simčič, Goriška Brda, Primorska | Suho | 0.75L', price: 95.00, image: '/menu-images/rdeca-vina/modri-pinot-opoka.png', categoryId: cats.rdecaVina.id, sortOrder: 5, modifierGroupIds: [] },
    { name: 'Merlot Keltis 2018', description: 'Butična klet Keltis, Bizeljsko-Sremič, Posavje | Suho | 0.75L', price: 48.00, image: '/menu-images/rdeca-vina/merlot-keltis.png', categoryId: cats.rdecaVina.id, sortOrder: 6, modifierGroupIds: [] },
    { name: 'Merlot Opoka 2019', description: 'Marjan Simčič, Goriška Brda, Primorska | Suho | 0.75L', price: 112.00, image: '/menu-images/rdeca-vina/merlot-opoka.png', categoryId: cats.rdecaVina.id, sortOrder: 7, modifierGroupIds: [] },
    { name: 'Cabernet Sauvignon Keltis 2018', description: 'Butična klet Keltis, Bizeljsko-Sremič, Posavje | Suho | 0.75L', price: 48.00, image: '/menu-images/rdeca-vina/cabernet-keltis.png', categoryId: cats.rdecaVina.id, sortOrder: 8, modifierGroupIds: [] },
    { name: 'Cabernet Sauvignon Pavo Limited Edition 2021', description: 'Dušan Kristančič, Goriška Brda, Primorska | Suho | 0.75L', price: 87.00, image: '/menu-images/rdeca-vina/cabernet-pavo.png', categoryId: cats.rdecaVina.id, sortOrder: 9, modifierGroupIds: [] },
    { name: 'Guerila Retro Selection 2020', description: 'Merlot, cabernet sauvignon, barbera | Klet Guerila, Vipavska dolina, Primorska | Suho | 0.75L', price: 50.00, image: '/menu-images/rdeca-vina/guerila-retro.png', categoryId: cats.rdecaVina.id, sortOrder: 10, modifierGroupIds: [] },
    { name: 'Duet Edi Simčič 2021', description: 'Merlot, cabernet sauvignon, cabernet franc | Edi Simčič, Goriška Brda, Primorska | Suho | 0.75L', price: 64.00, image: '/menu-images/rdeca-vina/duet-edi-simcic.png', categoryId: cats.rdecaVina.id, sortOrder: 11, modifierGroupIds: [] },
    { name: 'Duet Lex Edi Simčič 2018', description: 'Merlot, cabernet sauvignon, cabernet franc | Edi Simčič, Goriška Brda, Primorska | Suho | 1.50L', price: 200.00, image: '/menu-images/rdeca-vina/duet-lex-2018.png', categoryId: cats.rdecaVina.id, sortOrder: 12, modifierGroupIds: [] },
    { name: 'Duet Lex Edi Simčič 2020', description: 'Merlot, cabernet sauvignon, cabernet franc | Edi Simčič, Goriška Brda, Primorska | Suho | 0.75L', price: 95.00, image: '/menu-images/rdeca-vina/duet-lex-2020.png', categoryId: cats.rdecaVina.id, sortOrder: 13, modifierGroupIds: [] },
    { name: 'Carolina Rdeča 2018', description: 'Cabernet sauvignon, cabernet franc, merlot | Kmetija Jakončič, Goriška Brda, Primorska | Suho | 0.75L', price: 71.00, image: '/menu-images/rdeca-vina/carolina-rdeca.png', categoryId: cats.rdecaVina.id, sortOrder: 14, modifierGroupIds: [] },
    { name: 'Veliko Rdeče Movia 2015', description: 'Merlot, cabernet sauvignin, modri pinot | Klet Movia, Goriška Brda, Primorska | Suho | 0.75L', price: 93.00, image: '/menu-images/rdeca-vina/veliko-rdece-movia.png', categoryId: cats.rdecaVina.id, sortOrder: 15, modifierGroupIds: [] },

    // --- TUJA VINA ---
    { name: 'Pošip Premium Terra Madre 2021', description: 'Belo | Terra Madre, Južna Dalmacija, Hrvaška | Suho | 0.75L', price: 30.00, image: '/menu-images/tuja-vina/posip-terra-madre.png', categoryId: cats.tujaVina.id, sortOrder: 0, modifierGroupIds: [] },
    { name: 'Andreis Vinasmora 2020', description: 'Rdeče | Babič, Vinasmora, Primošten, Hrvaška | Suho | 0.75L', price: 30.00, image: '/menu-images/tuja-vina/andreis-vinasmora.png', categoryId: cats.tujaVina.id, sortOrder: 1, modifierGroupIds: [] },
    { name: 'Plavac Mali Premium Terra Madre 2017', description: 'Rdeče | Terra Madre, Južna Dalmacija, Hrvaška | Suho | 0.75L', price: 48.00, image: '/menu-images/tuja-vina/plavac-mali-terra-madre.png', categoryId: cats.tujaVina.id, sortOrder: 2, modifierGroupIds: [] },
    { name: 'Vranec Instinct 2019', description: 'Rdeče | Puklavec Family, Makedonija | Suho | 0.75L', price: 30.00, image: '/menu-images/tuja-vina/vranec-instinct.png', categoryId: cats.tujaVina.id, sortOrder: 3, modifierGroupIds: [] },
    { name: 'Chardonnay Where Dreams Have No End 2021', description: 'Belo | Jermann, Friuli Venezia Giulia, Italija | Suho | 0.75L', price: 110.00, image: '/menu-images/tuja-vina/jermann-dreams.png', categoryId: cats.tujaVina.id, sortOrder: 4, modifierGroupIds: [] },
    { name: 'Vintage Tunina 2022', description: 'Belo | Sauvignon, chardonnay, rebula gialla, malvazija | Jermann, Friuli Venezia Giulia, Italija | Suho | 0.75L', price: 110.00, image: '/menu-images/tuja-vina/vintage-tunina.png', categoryId: cats.tujaVina.id, sortOrder: 5, modifierGroupIds: [] },

    // --- LIKERSKO VINO ---
    { name: 'Keros Belo 2020 (0.05L)', description: 'Traminec | Vinarstvo Kerin, Straža nad Krškim, Dolenjska, Posavje | Sladko', price: 4.50, image: '/menu-images/likersko-vino/keros-belo-005.png', categoryId: cats.likerskoVino.id, sortOrder: 0, modifierGroupIds: [] },
    { name: 'Keros Belo 2020 (0.50L)', description: 'Traminec | Vinarstvo Kerin, Straža nad Krškim, Dolenjska, Posavje | Sladko', price: 45.00, image: '/menu-images/likersko-vino/keros-belo-050.png', categoryId: cats.likerskoVino.id, sortOrder: 1, modifierGroupIds: [] },
    { name: 'Keros Rdeče 2018 (0.05L)', description: 'Modra frankinja | Vinarstvo Kerin, Straža nad Krškim, Dolenjska, Posavje | Sladko', price: 4.50, image: '/menu-images/likersko-vino/keros-rdece-005.png', categoryId: cats.likerskoVino.id, sortOrder: 2, modifierGroupIds: [] },
    { name: 'Keros Rdeče 2018 (0.50L)', description: 'Modra frankinja | Vinarstvo Kerin, Straža nad Krškim, Dolenjska, Posavje | Sladko', price: 45.00, image: '/menu-images/likersko-vino/keros-rdece-050.png', categoryId: cats.likerskoVino.id, sortOrder: 3, modifierGroupIds: [] },
    { name: 'Veliko Rdeče Movia 2012', description: 'Merlot, cabernet sauvignin, modri pinot | Klet Movia, Goriška Brda, Primorska | Suho | 3.00L', price: 360.00, image: '/menu-images/likersko-vino/veliko-rdece-2012.png', categoryId: cats.likerskoVino.id, sortOrder: 4, modifierGroupIds: [] },
    { name: 'Sladki Refošk (kozarec)', description: 'Vina Koper, Slovenska Istra, Primorska | Sladko | 0.10L', price: 5.00, image: '/menu-images/likersko-vino/sladki-refosk-kozarec.png', categoryId: cats.likerskoVino.id, sortOrder: 5, modifierGroupIds: [] },
    { name: 'Sladki Refošk (0.50L)', description: 'Vina Koper, Slovenska Istra, Primorska | Sladko | 0.50L', price: 25.00, image: '/menu-images/likersko-vino/sladki-refosk-050.png', categoryId: cats.likerskoVino.id, sortOrder: 6, modifierGroupIds: [] },
  ]
}
