name: ✨ Feature Request
description: Predlagaj novo funkcijo
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Kateri problem rešuje ta funkcija?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Predlagana rešitev
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Prioriteta
      options:
        - Nizka
        - Srednja
        - Visoka
    validations:
      required: true
