#!/bin/bash
# Replace placeholder images with AI-generated images
# Run when API rate limit has reset: bash replace-with-ai.sh
# This only replaces images that are placeholders (generated by generate-placeholders.mjs)

set -e

IMAGES_DIR="/home/z/my-project/public/menu-images"

# List of 54 items that had placeholder images
ITEMS=(
  "ajdova-kasa|Ajdova kaša|bowl of buckwheat porridge, Slovenian traditional dish"
  "bbq-burger|BBQ burger|BBQ burger with grilled patty, BBQ sauce, lettuce, tomato, cheese"
  "burger-z-jajcem-in-slanino|Burger z jajcem in slanino|burger with fried egg and bacon, gourmet"
  "caprese-solata|Caprese solata|Caprese salad with fresh mozzarella, tomatoes, basil, olive oil"
  "cezarjeva-solata-s-kozicami|Cezarjeva solata s kozicami|Caesar salad with grilled shrimp, parmesan, croutons"
  "chili-burger|Chili burger|spicy chili burger with jalapenos, chili sauce, cheese"
  "club-sendvic-s-piscancem|Club sendvič s piščancem|club sandwich with chicken, bacon, lettuce, tomato, three layers"
  "domace-pecenice-s-kislim-zeljem|Domače pečenice s kislim zeljem|home-style roasted pork sausages with sauerkraut, Slovenian"
  "domino-kocke|Domino kocke|domino cube chocolate dessert, elegant patisserie"
  "file-brancina|File brancina|pan-seared sea bass fillet, Mediterranean style, white plate"
  "file-lososa-z-zara|File lososa z žara|grilled salmon fillet, grill marks, lemon garnish"
  "francoski-toast|Francoski toast|French toast with berries, powdered sugar, maple syrup"
  "granola-z-jogurtom|Granola z jogurtom|granola bowl with yogurt, fresh berries, honey drizzle"
  "havajska-pica|Havajska pica|Hawaiian pizza with ham and pineapple, melted cheese"
  "hrenovke-na-zaru|Hrenovke na žaru|grilled hot dogs with mustard, Slovenian style"
  "idrijski-zlikrofi|Idrijski žlikrofi|Idrijski zlikrofi, Slovenian filled dumplings, traditional"
  "jajcni-benedikt|Jajčni benedikt|Eggs Benedict with hollandaise sauce, ham, English muffin"
  "kava-in-krof|Kava in krof|coffee and donut, espresso with glazed doughnut, breakfast"
  "klobase-na-zaru|Klobase na žaru|grilled sausages with mustard and horseradish, BBQ style"
  "kmecka-pica|Kmečka pica|rustic farmhouse pizza with various toppings, traditional style"
  "kmecki-kroznik|Kmečki krožnik|farmhouse platter with meats, cheese, pickles, bread, Slovenian"
  "krofi-s-pomarancno-marmelado|Krofi s pomarančno marmelado|doughnuts filled with orange marmalade, powdered sugar"
  "krompirjevi-kroketi|Krompirjevi kroketi|golden potato croquettes, crispy fried, side dish"
  "krvavica-s-kislim-zeljem|Krvavica s kislim zeljem|blood sausage with sauerkraut, Slovenian traditional"
  "ledeni-desert|Ledeni desert|frozen dessert, ice cream sundae with chocolate sauce, berries"
  "medaljoni-iz-govedine|Medaljoni iz govedine|beef medallions, tenderloin steak, gourmet presentation"
  "mini-burger-s-pomfri|Mini burger s pomfri|mini burger sliders with french fries, casual dining"
  "mlinci|Mlinci|mlinci, traditional Slovenian flatbread pasta"
  "njoki|Njoki|potato gnocchi with sauce, Italian-Slovenian dish"
  "obara-z-ajdovo-kaso|Obara z ajdovo kašo|Slovenian stew with buckwheat porridge, hearty traditional"
  "ocvrti-lignji-s-tartarsko-omako|Ocvrti lignji s tartarsko omako|fried calamari with tartar sauce, lemon wedge"
  "ocvrtki|Ocvrtki|Slovenian fried dough fritters, golden crispy, traditional"
  "penne-s-piscancem-in-curryjem|Penne s piščancem in curryjem|penne pasta with chicken and curry sauce, creamy"
  "pikantne-klobase|Pikantne klobase|spicy sausages grilled with peppers, chili flakes"
  "piscancji-file-na-zaru|Piščančji file na žaru|grilled chicken breast fillet, grill marks, herbs"
  "piscancji-file-v-parmezani|Piščančji file v parmezani|chicken parmesan with melted cheese, tomato sauce"
  "piscancji-nugeti-s-pomfri|Piščančji nugeti s pomfri|chicken nuggets with french fries, dipping sauces"
  "potica|Potica|Slovenian potica, traditional walnut roll cake, sliced, festive"
  "prekmurska-gibanica|Prekmurska gibanica|Prekmurska gibanica, Slovenian layered cake with poppy seeds, cottage cheese, walnuts, apples"
  "rezanci-z-gobami|Rezanci z gobami|noodles with wild mushrooms, creamy sauce, herbs garnish"
  "rizota-s-tartufi|Rižota s tartufi|truffle risotto, black truffle shavings, creamy Italian style"
  "rizota-s-sparglji|Rižota s šparglji|asparagus risotto, green asparagus tips, parmesan, creamy"
  "rizota-z-buckami-in-feto|Rižota z bučkami in feto|zucchini and feta risotto, Mediterranean style, fresh herbs"
  "sladoled-tri-okuse|Sladoled tri okuse|three scoops of ice cream, vanilla chocolate strawberry"
  "sladoled-za-otroke|Sladoled za otroke|kids ice cream sundae, colorful sprinkles, fun presentation"
  "solata-z-avokadom-in-kozicami|Solata z avokadom in kozicami|avocado and shrimp salad, fresh greens, citrus dressing"
  "solata-z-grilanim-sirom|Solata z grilanim sirom|grilled cheese salad, warm halloumi on mixed greens"
  "svinjska-rebra-z-zara|Svinjska rebra z žara|grilled pork ribs, BBQ glaze, smoky grill marks"
  "tagliatelle-s-tartufi|Tagliatelle s tartufi|tagliatelle pasta with truffles, black truffle shavings"
  "tunina-pica|Tunina pica|tuna pizza with onions, capers, olive oil, Mediterranean style"
  "sopska-solata|Šopska solata|Shopska salad with tomatoes, cucumbers, peppers, feta cheese"
  "stirje-siri|Štirje siri|four cheese pizza, melted mozzarella, gorgonzola, parmesan"
  "zar-deska-za-dve|Žar deska za dve|grilled meat platter for two, various grilled meats"
  "zar-zelenjava|Žar zelenjava|grilled vegetables, zucchini, peppers, eggplant, asparagus"
)

echo "=== Replacing placeholder images with AI-generated images ==="
echo "Total items: ${#ITEMS[@]}"
echo ""

SUCCESS=0
FAILED=0

for item in "${ITEMS[@]}"; do
  IFS='|' read -r filename name prompt <<< "$item"
  OUTPUT="$IMAGES_DIR/$filename.png"
  
  echo "[$((SUCCESS+FAILED+1))/${#ITEMS[@]}] Generating: $name"
  
  if z-ai-generate -p "Professional food photography of $prompt, restaurant dish, warm lighting, white plate, elegant presentation, high quality, 4k" -o "$OUTPUT" -s 864x1152 2>/dev/null; then
    echo "  ✓ Saved: $OUTPUT"
    SUCCESS=$((SUCCESS+1))
  else
    echo "  ✗ FAILED: $name"
    FAILED=$((FAILED+1))
  fi
  
  # Wait 5 seconds between generations to avoid rate limiting
  sleep 5
done

echo ""
echo "=== DONE ==="
echo "Success: $SUCCESS"
echo "Failed: $FAILED"
