// =====================================================================
// RECEPTI ZA HRANO - RestorantOS - Glavne jedi, testenine, rižote, kalamari, ribje jedi
// =====================================================================

import type { InvItem, RecipeEntry } from '../types'

export function buildGlavneJediRecipes(inv: Record<string, InvItem>): RecipeEntry[] {
  const {
    invAnanas,
    invBeefsteak,
    invBBQOmaka,
    invCebula,
    invCurryPrah,
    invDomacaSunka,
    invGovedinaBograch,
    invGovedinaZaGolaz,
    invGauda,
    invGorgonzola,
    invJajca,
    invKalamari,
    invKorenje,
    invKrompir,
    invKruhoveRezine,
    invKuhanPrsut,
    invLosos,
    invMletnoMeso,
    invMoka,
    invMelancani,
    invMozzarella,
    invMešanaZelenjava,
    invPaprika,
    invParmezan,
    invPelati,
    invPiscancjiFile,
    invPrsut,
    invPiscanecCeli,
    invPljucnaPecenka,
    invPuramjiFile,
    invRebra,
    invRiz,
    invRostbeef,
    invRizeviRezanci,
    invSampinjoni,
    invSladkaSmetana,
    invSpageti,
    invSvinjskaKraca,
    invSvinjskaPecenko,
    invSvinjskiZrezek,
    invTatarskaOmaka,
    invTartufi,
    invTelecjaPrsa,
    invBucke,
    invArasidi,
    invGamberi,
    invBlitva,
    invOslic,
    invPommesFrites,
    invFilePostrvi,
    invFileOrade,
    invFileBrancina,
    invOlivnoOlje,
    invPecenaKlobasa,
    invKrvavica,
    invZelje,
  } = inv

  return [
    // --- GLAVNE JEDI ---
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invTelecjaPrsa.id, quantityPerServing: 0.3, unit: 'kg', notes: 'telečja prsa' },
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invKrompir.id, quantityPerServing: 0.3, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Pečena svinjska krača', ingredientId: invSvinjskaKraca.id, quantityPerServing: 1, unit: 'kos', notes: '1500g krača' },
    { menuItemName: 'Svinjska pečenka', ingredientId: invSvinjskaPecenko.id, quantityPerServing: 0.45, unit: 'kg', notes: '450g pečenka' },
    { menuItemName: 'Svinjska pečenka', ingredientId: invKrompir.id, quantityPerServing: 0.3, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Telečja pečenka', ingredientId: invTelecjaPrsa.id, quantityPerServing: 0.45, unit: 'kg', notes: '450g telečja' },
    { menuItemName: 'Rumpsteak', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rumpsteak' },
    { menuItemName: 'BBQ rebrca', ingredientId: invRebra.id, quantityPerServing: 0.5, unit: 'kg', notes: '500g rebra' },
    { menuItemName: 'BBQ rebrca', ingredientId: invBBQOmaka.id, quantityPerServing: 1, unit: 'kos', notes: 'BBQ omaka' },
    { menuItemName: 'Beefsteak v poprovi omaki', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g beefsteak' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g beefsteak' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invGovedinaBograch.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g govedina' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invPaprika.id, quantityPerServing: 0.1, unit: 'kg', notes: 'paprika' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invCebula.id, quantityPerServing: 0.05, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Goveji golaž v kotličku', ingredientId: invGovedinaZaGolaz.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g govedina' },
    { menuItemName: 'Goveji golaž v kotličku', ingredientId: invKruhoveRezine.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kruhova rezina' },
    { menuItemName: 'Dunajski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Pariški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'Kraški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Kraški zrezek', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Kraški zrezek', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Naravni zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Zrezek z gobami', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Zrezek z gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invDomacaSunka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'šunka' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invGauda.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Zrezek v curry omaki', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Sirov zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Sirov zrezek', ingredientId: invGauda.id, quantityPerServing: 0.1, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Hawaii zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hawaii zrezek', ingredientId: invAnanas.id, quantityPerServing: 1, unit: 'kos', notes: 'ananas' },
    { menuItemName: 'Tagliata na rukoli', ingredientId: invRostbeef.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rostbeef' },
    { menuItemName: 'Rostbeef', ingredientId: invRostbeef.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rostbeef' },
    { menuItemName: 'Žar tris', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.15, unit: 'kg', notes: 'svinjski kare' },
    { menuItemName: 'Žar tris', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.1, unit: 'kg', notes: 'piščančja prsa' },
    { menuItemName: 'Žar tris', ingredientId: invRostbeef.id, quantityPerServing: 0.1, unit: 'kg', notes: 'rostbeef' },
    { menuItemName: 'Ocvrt pišanec', ingredientId: invPiscanecCeli.id, quantityPerServing: 1, unit: 'kos', notes: 'cel pišanec' },
    { menuItemName: 'Pohančki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.25, unit: 'kg', notes: 'puranji/piščančji' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invPecenaKlobasa.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g pečenica' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invZelje.id, quantityPerServing: 0.15, unit: 'kg', notes: 'zelje' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'krompir' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invKrvavica.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g krvavica' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invZelje.id, quantityPerServing: 0.15, unit: 'kg', notes: 'zelje' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'krompir' },

    // --- TESTENINE ---
    { menuItemName: 'Bolognese', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Bolognese', ingredientId: invMletnoMeso.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mletno meso' },
    { menuItemName: 'Bolognese', ingredientId: invPelati.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Carbonara', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Carbonara', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Carbonara', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'Napoli', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Napoli', ingredientId: invPelati.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Z gobami', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.15, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'S tartufi', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S tartufi', ingredientId: invTartufi.id, quantityPerServing: 1, unit: 'kos', notes: 'tartufi' },
    { menuItemName: 'S tartufi', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'V gorgonzolini omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'V gorgonzolini omaki', ingredientId: invGorgonzola.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gorgonzola' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invCurryPrah.id, quantityPerServing: 1, unit: 'kos', notes: 'curry' },
    { menuItemName: 'V smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'V smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invKalamari.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kalamari' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invGamberi.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invKalamari.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kalamari' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'S pljučno pečenko in zelenjavo', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S pljučno pečenko in zelenjavo', ingredientId: invPljucnaPecenka.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pljučna pečenka' },
    { menuItemName: 'Sicilijana', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Sicilijana', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moccarela' },
    { menuItemName: 'Sicilijana', ingredientId: invMelancani.id, quantityPerServing: 0.1, unit: 'kg', notes: 'melancani' },
    { menuItemName: 'Z gamberi na rdeče ali belo', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z gamberi na rdeče ali belo', ingredientId: invGamberi.id, quantityPerServing: 0.15, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'S piščancem', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S piščancem', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'piščanec' },
    { menuItemName: 'S piščancem', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moccarela' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invRizeviRezanci.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riževi rezanci' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invKorenje.id, quantityPerServing: 0.05, unit: 'kg', notes: 'korenje' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invRizeviRezanci.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riževi rezanci' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'piščanec' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },

    // --- RIŽOTE ---
    { menuItemName: 'Morska rižota', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Morska rižota', ingredientId: invKalamari.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kalamari' },
    { menuItemName: 'Morska rižota', ingredientId: invGamberi.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'Rižota z gobami', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Rižota z gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.15, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'Rižota s puranom in papriko', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Rižota s puranom in papriko', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran' },
    { menuItemName: 'Rižota s puranom in papriko', ingredientId: invPaprika.id, quantityPerServing: 0.1, unit: 'kg', notes: 'paprika' },
    { menuItemName: 'Zelenjavna rižota', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Zelenjavna rižota', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Rižota z gamberi in mešanimi gobami', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Rižota z gamberi in mešanimi gobami', ingredientId: invGamberi.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'Rižota z gamberi in mešanimi gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gobe' },

    // --- KALAMARI ---
    { menuItemName: 'Ocvrti kalamari', ingredientId: invKalamari.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g kalamari' },
    { menuItemName: 'Ocvrti kalamari', ingredientId: invMoka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'za paniranje' },
    { menuItemName: 'Ocvrti kalamari', ingredientId: invTatarskaOmaka.id, quantityPerServing: 1, unit: 'kos', notes: 'tatarska omaka' },
    { menuItemName: 'Kalamari na žaru', ingredientId: invKalamari.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g kalamari' },
    { menuItemName: 'Kalamari na žaru', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Kalamari na žaru', ingredientId: invBlitva.id, quantityPerServing: 0.1, unit: 'kg', notes: 'blitva' },
    { menuItemName: 'Polnjeni kalamari po dunajsko', ingredientId: invKalamari.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g kalamari' },
    { menuItemName: 'Polnjeni kalamari po dunajsko', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Polnjeni kalamari po dunajsko', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },

    // --- RIBJE JEDI ---
    { menuItemName: 'Losos', ingredientId: invLosos.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g losos' },
    { menuItemName: 'Losos', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Losos', ingredientId: invBlitva.id, quantityPerServing: 0.1, unit: 'kg', notes: 'blitva' },
    { menuItemName: 'Gamberi po pariško', ingredientId: invGamberi.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g gamberi' },
    { menuItemName: 'Ocvrt oslič s prilogo', ingredientId: invOslic.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g oslič' },
    { menuItemName: 'Ocvrt oslič s prilogo', ingredientId: invPommesFrites.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'File postrvi', ingredientId: invFilePostrvi.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g postrv' },
    { menuItemName: 'File orade', ingredientId: invFileOrade.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g orada' },
    { menuItemName: 'File brancina na žaru', ingredientId: invFileBrancina.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g brancin' },
  ]
}
