// =====================================================================
// RECEPTI ZA HRANO - RestorantOS - Solate, pizze, burgerji, vegetarijanske,
//   palačinke, otroške jedi, malice
// =====================================================================

import type { InvItem, RecipeEntry } from '../types'

export function buildPiceDrugoRecipes(inv: Record<string, InvItem>): RecipeEntry[] {
  const {
    invAnanas,
    invArasidi,
    invBBQOmaka,
    invBelaCokolada,
    invBucke,
    invBurgerPatty,
    invCebula,
    invCesen,
    invCheddarSir,
    invCurryPrah,
    invDomacaSunka,
    invEdamec,
    invFerreroRocher,
    invFetaSir,
    invGauda,
    invGorgonzola,
    invGovedinaBograch,
    invGovedinaZaGolaz,
    invJagodniPire,
    invJajca,
    invKakavZaPalačinke,
    invKinderBueno,
    invKokosovaMoka,
    invKorenje,
    invKozjiSir,
    invKrompir,
    invKuhanPrsut,
    invLinoLada,
    invMandM,
    invMandlji,
    invMelancani,
    invMletnoMeso,
    invMoka,
    invMokaPalacinke,
    invMozzarella,
    invNutella,
    invOlive,
    invOlivnoOlje,
    invOslic,
    invPaprika,
    invParadiznik,
    invParmezan,
    invPelati,
    invPesto,
    invPiscancjiFile,
    invPlazmaPiskot,
    invPommesFrites,
    invPrsut,
    invPuramjiFile,
    invRaffaello,
    invRebra,
    invRostbeef,
    invRukola,
    invSampinjoni,
    invSlanina,
    invSnickers,
    invSolata,
    invSuhaSalama,
    invSvinjskaPecenko,
    invSvinjskiZrezek,
    invTartufi,
    invTatarskaOmaka,
    invTestoZaPica,
    invSpageti,
    invTunaKos,
    invMešanaZelenjava,
  } = inv

  return [
    // --- SOLATE ---
    { menuItemName: 'Solata Kraljica', ingredientId: invSolata.id, quantityPerServing: 0.3, unit: 'kg', notes: 'mešana solata' },
    { menuItemName: 'Solata Kraljica', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Solata Kraljica', ingredientId: invTatarskaOmaka.id, quantityPerServing: 1, unit: 'kos', notes: 'tatarska omaka' },
    { menuItemName: 'Cezarjeva solata', ingredientId: invSolata.id, quantityPerServing: 0.2, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Cezarjeva solata', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'piščanec' },
    { menuItemName: 'Cezarjeva solata', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'parmezan' },
    { menuItemName: 'Grška solata', ingredientId: invSolata.id, quantityPerServing: 0.15, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Grška solata', ingredientId: invParadiznik.id, quantityPerServing: 0.1, unit: 'kg', notes: 'paradižnik' },
    { menuItemName: 'Grška solata', ingredientId: invFetaSir.id, quantityPerServing: 0.1, unit: 'kg', notes: 'feta sir' },
    { menuItemName: 'Grška solata', ingredientId: invOlive.id, quantityPerServing: 0.03, unit: 'kg', notes: 'olive' },
    { menuItemName: 'Solata rukola s parmezanom', ingredientId: invRukola.id, quantityPerServing: 1, unit: 'kos', notes: 'rukola' },
    { menuItemName: 'Solata rukola s parmezanom', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'parmezan' },
    { menuItemName: 'Mešana solata s tuno', ingredientId: invSolata.id, quantityPerServing: 0.3, unit: 'kg', notes: 'mešana solata' },
    { menuItemName: 'Mešana solata s tuno', ingredientId: invTunaKos.id, quantityPerServing: 0.15, unit: 'kg', notes: 'tuna' },

    // --- PIZZE ---
    { menuItemName: 'Margerita', ingredientId: invTestoZaPica.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'Margerita', ingredientId: invPelati.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Margerita', ingredientId: invMozzarella.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'Hišna pica', ingredientId: invTestoZaPica.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'Hišna pica', ingredientId: invPelati.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Hišna pica', ingredientId: invMozzarella.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'Hišna pica', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'kuhan pršut' },
    { menuItemName: 'Hišna pica', ingredientId: invDomacaSunka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'domača šunka' },
    { menuItemName: 'Hišna pica', ingredientId: invSuhaSalama.id, quantityPerServing: 0.05, unit: 'kg', notes: 'salama' },
    { menuItemName: 'Hišna pica', ingredientId: invSlanina.id, quantityPerServing: 0.05, unit: 'kg', notes: 'slanina' },
    { menuItemName: 'Hišna pica', ingredientId: invSampinjoni.id, quantityPerServing: 0.05, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'Kraška', ingredientId: invTestoZaPica.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'Kraška', ingredientId: invPelati.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Kraška', ingredientId: invMozzarella.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'Kraška', ingredientId: invPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Kraška', ingredientId: invSampinjoni.id, quantityPerServing: 0.05, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'S tuno', ingredientId: invTestoZaPica.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'S tuno', ingredientId: invPelati.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'S tuno', ingredientId: invMozzarella.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'S tuno', ingredientId: invTunaKos.id, quantityPerServing: 0.1, unit: 'kg', notes: 'tuna' },
    { menuItemName: 'Štirje siri', ingredientId: invTestoZaPica.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'Štirje siri', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'Štirje siri', ingredientId: invGorgonzola.id, quantityPerServing: 0.05, unit: 'kg', notes: 'gorgonzola' },
    { menuItemName: 'Štirje siri', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'gauda' },
    { menuItemName: 'Štirje siri', ingredientId: invEdamec.id, quantityPerServing: 0.05, unit: 'kg', notes: 'edamec' },

    // --- BURGERJI ---
    { menuItemName: 'Hišni burger', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g goveji patty' },
    { menuItemName: 'Hišni burger', ingredientId: invKozjiSir.id, quantityPerServing: 0.05, unit: 'kg', notes: 'kozji sir' },
    { menuItemName: 'Hišni burger', ingredientId: invSlanina.id, quantityPerServing: 0.05, unit: 'kg', notes: 'slanina' },
    { menuItemName: 'Hišni burger', ingredientId: invCebula.id, quantityPerServing: 0.03, unit: 'kg', notes: 'karamelizirana čebula' },
    { menuItemName: 'The classic', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g goveji patty' },
    { menuItemName: 'The classic', ingredientId: invCheddarSir.id, quantityPerServing: 0.05, unit: 'kg', notes: 'cheddar' },
    { menuItemName: 'The classic', ingredientId: invSolata.id, quantityPerServing: 0.03, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Big BOSS', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g goveji patty' },
    { menuItemName: 'Big BOSS', ingredientId: invRostbeef.id, quantityPerServing: 0.05, unit: 'kg', notes: 'rostbeef' },
    { menuItemName: 'Big BOSS', ingredientId: invTartufi.id, quantityPerServing: 1, unit: 'kos', notes: 'tartufina majoneza' },
    { menuItemName: 'Cheese please', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g goveji patty' },
    { menuItemName: 'Cheese please', ingredientId: invCheddarSir.id, quantityPerServing: 0.05, unit: 'kg', notes: 'cheddar' },
    { menuItemName: 'Green garden', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g patty' },
    { menuItemName: 'Green garden', ingredientId: invPesto.id, quantityPerServing: 1, unit: 'kos', notes: 'bazilični pesto' },
    { menuItemName: 'Green garden', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Crispy chicken burger', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.18, unit: 'kg', notes: '180g piščančja prsa' },
    { menuItemName: 'Crispy chicken burger', ingredientId: invCheddarSir.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Fit burger', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.18, unit: 'kg', notes: '180g piščančja prsa' },
    { menuItemName: 'Fit burger', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Fit burger', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },

    // --- VEGETARIJANSKE ---
    { menuItemName: 'Zelenjavni zrezki', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Sojini polpeti', ingredientId: invMletnoMeso.id, quantityPerServing: 0.15, unit: 'kg', notes: 'sojini polpeti' },
    { menuItemName: 'Bučke na žaru', ingredientId: invBucke.id, quantityPerServing: 0.25, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Bučke na žaru', ingredientId: invCesen.id, quantityPerServing: 0.01, unit: 'kg', notes: 'česen' },
    { menuItemName: 'Bučke na žaru', ingredientId: invOlivnoOlje.id, quantityPerServing: 0.02, unit: 'L', notes: 'olivno olje' },
    { menuItemName: 'Ocvrte bučke', ingredientId: invBucke.id, quantityPerServing: 0.25, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Ocvrti melancani', ingredientId: invMelancani.id, quantityPerServing: 0.25, unit: 'kg', notes: 'melancani' },
    { menuItemName: 'Vegetarijanska plošča', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Vegetarijanska plošča', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'šampinjoni' },

    // --- PALAČINKE ---
    { menuItemName: 'Hišna sladica', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka' },
    { menuItemName: 'Hišna sladica', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Hišna sladica', ingredientId: invJagodniPire.id, quantityPerServing: 0.05, unit: 'kg', notes: 'jagodni pire' },
    { menuItemName: 'Hišna sladica', ingredientId: invLinoLada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Lino Lada' },
    { menuItemName: 'Hišna sladica', ingredientId: invBelaCokolada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'bela čokolada' },
    { menuItemName: 'Hišna sladica', ingredientId: invPlazmaPiskot.id, quantityPerServing: 0.02, unit: 'kg', notes: 'Plazma biskvit' },
    { menuItemName: 'Raffaello', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka' },
    { menuItemName: 'Raffaello', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Raffaello', ingredientId: invBelaCokolada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'bela čokolada' },
    { menuItemName: 'Raffaello', ingredientId: invLinoLada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Lino Lada' },
    { menuItemName: 'Raffaello', ingredientId: invMandlji.id, quantityPerServing: 0.02, unit: 'kg', notes: 'mandlji' },
    { menuItemName: 'Raffaello', ingredientId: invKokosovaMoka.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kokosova moka' },
    { menuItemName: 'Raffaello', ingredientId: invRaffaello.id, quantityPerServing: 1, unit: 'kos', notes: 'Raffaello kroglica' },
    { menuItemName: 'Kinder Bueno', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Kinder Bueno', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Kinder Bueno', ingredientId: invKakavZaPalačinke.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kakav' },
    { menuItemName: 'Kinder Bueno', ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čokoladno-lešnikova krema' },
    { menuItemName: 'Kinder Bueno', ingredientId: invKinderBueno.id, quantityPerServing: 1, unit: 'kos', notes: 'Kinder Bueno' },
    { menuItemName: 'Snickers', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Snickers', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Snickers', ingredientId: invKakavZaPalačinke.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kakav' },
    { menuItemName: 'Snickers', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },
    { menuItemName: 'Snickers', ingredientId: invSnickers.id, quantityPerServing: 1, unit: 'kos', notes: 'Snickers' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čokoladno-lešnikova krema' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invMandlji.id, quantityPerServing: 0.02, unit: 'kg', notes: 'lešniki' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invFerreroRocher.id, quantityPerServing: 1, unit: 'kos', notes: 'Ferrero Rocher' },
    { menuItemName: "M&M's", ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: "M&M's", ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: "M&M's", ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Nutella' },
    { menuItemName: "M&M's", ingredientId: invMandM.id, quantityPerServing: 0.02, unit: 'kg', notes: "M&M's" },

    // --- OTROŠKE JEDI ---
    { menuItemName: 'Krožnik Miškolin', ingredientId: invGauda.id, quantityPerServing: 0.15, unit: 'kg', notes: 'ocvrti sir' },
    { menuItemName: 'Krožnik Miškolin', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Krožnik Korenjak', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.15, unit: 'kg', notes: 'dunajski zrezek' },
    { menuItemName: 'Krožnik Korenjak', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Otroški pohančki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran/piščanec' },
    { menuItemName: 'Otroški pohančki', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Pizza Malček', ingredientId: invTestoZaPica.id, quantityPerServing: 0.5, unit: 'kg', notes: 'manjše testo' },
    { menuItemName: 'Pizza Malček', ingredientId: invPelati.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Pizza Malček', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'mozzarella' },

    // --- MALICE (Dnevno kosilo) ---
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g zrezek' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g zrezek' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invRebra.id, quantityPerServing: 0.30, unit: 'kg', notes: '300g rebra' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invKrompir.id, quantityPerServing: 0.25, unit: 'kg', notes: 'pražen krompir' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.25, unit: 'kg', notes: 'piščančje perutničke' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invBBQOmaka.id, quantityPerServing: 0.05, unit: 'L', notes: 'BBQ omaka' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invSvinjskaPecenko.id, quantityPerServing: 0.30, unit: 'kg', notes: '300g pečenka' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invKrompir.id, quantityPerServing: 0.25, unit: 'kg', notes: 'pražen krompir' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invOslic.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g oslič' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invKrompir.id, quantityPerServing: 0.20, unit: 'kg', notes: 'krompirjeva solata' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invOslic.id, quantityPerServing: 0.15, unit: 'kg', notes: '150g oslič' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Ocvrti sir', ingredientId: invGauda.id, quantityPerServing: 0.15, unit: 'kg', notes: 'ocvrti sir' },
    { menuItemName: 'Malica - Ocvrti sir', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invSpageti.id, quantityPerServing: 0.15, unit: 'kg', notes: 'špageti' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invMletnoMeso.id, quantityPerServing: 0.10, unit: 'kg', notes: 'bolognese omaka' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invParadiznik.id, quantityPerServing: 0.05, unit: 'kg', notes: 'paradižnikova omaka' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invMletnoMeso.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mesni sir' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invSampinjoni.id, quantityPerServing: 0.03, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Malica - Bograč', ingredientId: invGovedinaBograch.id, quantityPerServing: 0.15, unit: 'kg', notes: 'govedina' },
    { menuItemName: 'Malica - Bograč', ingredientId: invParadiznik.id, quantityPerServing: 0.05, unit: 'kg', notes: 'paradižnik' },
    { menuItemName: 'Malica - Bograč', ingredientId: invCebula.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Malica - Bograč', ingredientId: invPaprika.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paprika' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invGovedinaZaGolaz.id, quantityPerServing: 0.15, unit: 'kg', notes: 'govedina' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invCebula.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invParadiznik.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paradižnikova omaka' },
  ]
}
