// =====================================================================
// RECEPTI ZA HRANO - RestorantOS (z Malicami, Palačinkami, Otroškimi jedmi)
// =====================================================================

import type { InvItem, RecipeEntry } from './types'

export function buildRestorantosRecipes(inv: Record<string, InvItem>): RecipeEntry[] {
  const {
    invAnanas,
    invArasidi,
    invBBQOmaka,
    invBeefsteak,
    invBelaCokolada,
    invBlitva,
    invBucke,
    invBurgerPatty,
    invCebula,
    invCesen,
    invCheddarSir,
    invCurryPrah,
    invDomacaSunka,
    invEdamec,
    invFerreroRocher,
    invFetaSir,
    invFileBrancina,
    invFileOrade,
    invFilePostrvi,
    invGamberi,
    invGauda,
    invGorgonzola,
    invGovedinaBograch,
    invGovedinaZaGolaz,
    invJagodniPire,
    invJajca,
    invKakavZaPalačinke,
    invKalamari,
    invKinderBueno,
    invKokosovaMoka,
    invKorenje,
    invKozjiSir,
    invKrompir,
    invKruhoveRezine,
    invKrvavica,
    invKuhanPrsut,
    invLinoLada,
    invLosos,
    invMandM,
    invMandlji,
    invMelancani,
    invMesnineIzbira,
    invMešanaZelenjava,
    invMletnoMeso,
    invMoka,
    invMokaPalacinke,
    invMozzarella,
    invNutella,
    invOlive,
    invOlivnoOlje,
    invOslic,
    invPaprika,
    invParadiznik,
    invParmezan,
    invPecenaKlobasa,
    invPelati,
    invPesto,
    invPiscancjiFile,
    invPiscanecCeli,
    invPlazmaPiskot,
    invPljucnaPecenka,
    invPommesFrites,
    invPrsut,
    invPuramjiFile,
    invRaffaello,
    invRebra,
    invRiz,
    invRizeviRezanci,
    invRostbeef,
    invRukola,
    invSampinjoni,
    invSiroviStrukelj,
    invSladkaSmetana,
    invSlanina,
    invSnickers,
    invSolata,
    invSpageti,
    invSuhaSalama,
    invSvinjskaKraca,
    invSvinjskaPecenko,
    invSvinjskiZrezek,
    invTartufi,
    invTatarskaOmaka,
    invTelecjaPrsa,
    invTestoZaPico,
    invTunaKos,
    invZelje
  } = inv

  const foodRecipes: RecipeEntry[] = [
    // --- HLAĐNE PREDJEDI ---
    { menuItemName: 'Domači narezek', ingredientId: invMesnineIzbira.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g mesnin' },
    { menuItemName: 'Domači narezek', ingredientId: invParmezan.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Pršut z olivami', ingredientId: invPrsut.id, quantityPerServing: 0.25, unit: 'kg', notes: 'kraški pršut' },
    { menuItemName: 'Pršut z olivami', ingredientId: invOlive.id, quantityPerServing: 0.05, unit: 'kg', notes: 'olive' },
    { menuItemName: 'Sirova plošča', ingredientId: invGorgonzola.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gorgonzola' },
    { menuItemName: 'Sirova plošča', ingredientId: invGauda.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gauda' },
    { menuItemName: 'Sirova plošča', ingredientId: invEdamec.id, quantityPerServing: 0.1, unit: 'kg', notes: 'edamec' },

    // --- TOPLE PREDJEDI ---
    { menuItemName: 'Ocvrti šampinjoni', ingredientId: invSampinjoni.id, quantityPerServing: 0.3, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Ocvrti šampinjoni', ingredientId: invMoka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'za paniranje' },
    { menuItemName: 'Ocvrti šampinjoni', ingredientId: invOlivnoOlje.id, quantityPerServing: 0.05, unit: 'L', notes: 'za cvrenje' },
    { menuItemName: 'Šampinjoni na žaru z gorgonzolo', ingredientId: invSampinjoni.id, quantityPerServing: 0.3, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Šampinjoni na žaru z gorgonzolo', ingredientId: invGorgonzola.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gorgonzola' },
    { menuItemName: 'Šampinjoni v gorgonzolni omaki', ingredientId: invSampinjoni.id, quantityPerServing: 0.3, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Šampinjoni v gorgonzolni omaki', ingredientId: invGorgonzola.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gorgonzola' },
    { menuItemName: 'Šampinjoni v gorgonzolni omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'Ocvrti sir s tatarsko omako', ingredientId: invGauda.id, quantityPerServing: 0.2, unit: 'kg', notes: 'sir za cvrenje' },
    { menuItemName: 'Ocvrti sir s tatarsko omako', ingredientId: invMoka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'za paniranje' },
    { menuItemName: 'Ocvrti sir s tatarsko omako', ingredientId: invTatarskaOmaka.id, quantityPerServing: 1, unit: 'kos', notes: 'tatarska omaka' },
    { menuItemName: 'Sirovi štruklji', ingredientId: invSiroviStrukelj.id, quantityPerServing: 3, unit: 'kos', notes: '3 kosi' },
    { menuItemName: 'Popečena slanina na rukoli', ingredientId: invSlanina.id, quantityPerServing: 0.15, unit: 'kg', notes: 'slanina' },
    { menuItemName: 'Popečena slanina na rukoli', ingredientId: invRukola.id, quantityPerServing: 1, unit: 'kos', notes: 'rukola' },
    { menuItemName: 'Dnevna kremna gobova juha', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'Dnevna kremna gobova juha', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'Goveja juha', ingredientId: invGovedinaZaGolaz.id, quantityPerServing: 0.05, unit: 'kg', notes: 'govedina' },
    { menuItemName: 'Goveja juha', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.1, unit: 'kg', notes: 'zelenjava' },

    // --- GLAVNE JEDI ---
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invTelecjaPrsa.id, quantityPerServing: 0.3, unit: 'kg', notes: 'telečja prsa' },
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invKrompir.id, quantityPerServing: 0.3, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Pečena svinjska krača', ingredientId: invSvinjskaKraca.id, quantityPerServing: 1, unit: 'kos', notes: '1500g krača' },
    { menuItemName: 'Svinjska pečenka', ingredientId: invSvinjskaPecenko.id, quantityPerServing: 0.45, unit: 'kg', notes: '450g pečenka' },
    { menuItemName: 'Svinjska pečenka', ingredientId: invKrompir.id, quantityPerServing: 0.3, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Telečja pečenka', ingredientId: invTelecjaPrsa.id, quantityPerServing: 0.45, unit: 'kg', notes: '450g telečja' },
    { menuItemName: 'Rumpsteak', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rumpsteak' },
    { menuItemName: 'BBQ rebrca', ingredientId: invRebra.id, quantityPerServing: 0.5, unit: 'kg', notes: '500g rebra' },
    { menuItemName: 'BBQ rebrca', ingredientId: invBBQOmaka.id, quantityPerServing: 1, unit: 'kos', notes: 'BBQ omaka' },
    { menuItemName: 'Beefsteak v poprovi omaki', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g beefsteak' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g beefsteak' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invGovedinaBograch.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g govedina' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invPaprika.id, quantityPerServing: 0.1, unit: 'kg', notes: 'paprika' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invCebula.id, quantityPerServing: 0.05, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Goveji golaž v kotličku', ingredientId: invGovedinaZaGolaz.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g govedina' },
    { menuItemName: 'Goveji golaž v kotličku', ingredientId: invKruhoveRezine.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kruhova rezina' },
    { menuItemName: 'Dunajski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Pariški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'Kraški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Kraški zrezek', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Kraški zrezek', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Naravni zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Zrezek z gobami', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Zrezek z gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invDomacaSunka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'šunka' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invGauda.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Zrezek v curry omaki', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Sirov zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Sirov zrezek', ingredientId: invGauda.id, quantityPerServing: 0.1, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Hawaii zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hawaii zrezek', ingredientId: invAnanas.id, quantityPerServing: 1, unit: 'kos', notes: 'ananas' },
    { menuItemName: 'Tagliata na rukoli', ingredientId: invRostbeef.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rostbeef' },
    { menuItemName: 'Rostbeef', ingredientId: invRostbeef.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rostbeef' },
    { menuItemName: 'Žar tris', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.15, unit: 'kg', notes: 'svinjski kare' },
    { menuItemName: 'Žar tris', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.1, unit: 'kg', notes: 'piščančja prsa' },
    { menuItemName: 'Žar tris', ingredientId: invRostbeef.id, quantityPerServing: 0.1, unit: 'kg', notes: 'rostbeef' },
    { menuItemName: 'Ocvrt pišanec', ingredientId: invPiscanecCeli.id, quantityPerServing: 1, unit: 'kos', notes: 'cel pišanec' },
    { menuItemName: 'Pohančki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.25, unit: 'kg', notes: 'puranji/piščančji' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invPecenaKlobasa.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g pečenica' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invZelje.id, quantityPerServing: 0.15, unit: 'kg', notes: 'zelje' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'krompir' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invKrvavica.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g krvavica' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invZelje.id, quantityPerServing: 0.15, unit: 'kg', notes: 'zelje' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'krompir' },

    // --- TESTENINE ---
    { menuItemName: 'Bolognese', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Bolognese', ingredientId: invMletnoMeso.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mletno meso' },
    { menuItemName: 'Bolognese', ingredientId: invPelati.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Carbonara', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Carbonara', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Carbonara', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'Napoli', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Napoli', ingredientId: invPelati.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Z gobami', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.15, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'S tartufi', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S tartufi', ingredientId: invTartufi.id, quantityPerServing: 1, unit: 'kos', notes: 'tartufi' },
    { menuItemName: 'S tartufi', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'V gorgonzolini omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'V gorgonzolini omaki', ingredientId: invGorgonzola.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gorgonzola' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invCurryPrah.id, quantityPerServing: 1, unit: 'kos', notes: 'curry' },
    { menuItemName: 'V smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'V smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invKalamari.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kalamari' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invGamberi.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invKalamari.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kalamari' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'S pljučno pečenko in zelenjavo', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S pljučno pečenko in zelenjavo', ingredientId: invPljucnaPecenka.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pljučna pečenka' },
    { menuItemName: 'Sicilijana', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Sicilijana', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moccarela' },
    { menuItemName: 'Sicilijana', ingredientId: invMelancani.id, quantityPerServing: 0.1, unit: 'kg', notes: 'melancani' },
    { menuItemName: 'Z gamberi na rdeče ali belo', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z gamberi na rdeče ali belo', ingredientId: invGamberi.id, quantityPerServing: 0.15, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'S piščancem', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S piščancem', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'piščanec' },
    { menuItemName: 'S piščancem', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moccarela' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invRizeviRezanci.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riževi rezanci' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invKorenje.id, quantityPerServing: 0.05, unit: 'kg', notes: 'korenje' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invRizeviRezanci.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riževi rezanci' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'piščanec' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },

    // --- RIŽOTE ---
    { menuItemName: 'Morska rižota', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Morska rižota', ingredientId: invKalamari.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kalamari' },
    { menuItemName: 'Morska rižota', ingredientId: invGamberi.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'Rižota z gobami', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Rižota z gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.15, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'Rižota s puranom in papriko', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Rižota s puranom in papriko', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran' },
    { menuItemName: 'Rižota s puranom in papriko', ingredientId: invPaprika.id, quantityPerServing: 0.1, unit: 'kg', notes: 'paprika' },
    { menuItemName: 'Zelenjavna rižota', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Zelenjavna rižota', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Rižota z gamberi in mešanimi gobami', ingredientId: invRiz.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riž' },
    { menuItemName: 'Rižota z gamberi in mešanimi gobami', ingredientId: invGamberi.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'Rižota z gamberi in mešanimi gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gobe' },

    // --- KALAMARI ---
    { menuItemName: 'Ocvrti kalamari', ingredientId: invKalamari.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g kalamari' },
    { menuItemName: 'Ocvrti kalamari', ingredientId: invMoka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'za paniranje' },
    { menuItemName: 'Ocvrti kalamari', ingredientId: invTatarskaOmaka.id, quantityPerServing: 1, unit: 'kos', notes: 'tatarska omaka' },
    { menuItemName: 'Kalamari na žaru', ingredientId: invKalamari.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g kalamari' },
    { menuItemName: 'Kalamari na žaru', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Kalamari na žaru', ingredientId: invBlitva.id, quantityPerServing: 0.1, unit: 'kg', notes: 'blitva' },
    { menuItemName: 'Polnjeni kalamari po dunajsko', ingredientId: invKalamari.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g kalamari' },
    { menuItemName: 'Polnjeni kalamari po dunajsko', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Polnjeni kalamari po dunajsko', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },

    // --- RIBJE JEDI ---
    { menuItemName: 'Losos', ingredientId: invLosos.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g losos' },
    { menuItemName: 'Losos', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Losos', ingredientId: invBlitva.id, quantityPerServing: 0.1, unit: 'kg', notes: 'blitva' },
    { menuItemName: 'Gamberi po pariško', ingredientId: invGamberi.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g gamberi' },
    { menuItemName: 'Ocvrt oslič s prilogo', ingredientId: invOslic.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g oslič' },
    { menuItemName: 'Ocvrt oslič s prilogo', ingredientId: invPommesFrites.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'File postrvi', ingredientId: invFilePostrvi.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g postrv' },
    { menuItemName: 'File orade', ingredientId: invFileOrade.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g orada' },
    { menuItemName: 'File brancina na žaru', ingredientId: invFileBrancina.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g brancin' },

    // --- SOLATE ---
    { menuItemName: 'Solata Kraljica', ingredientId: invSolata.id, quantityPerServing: 0.3, unit: 'kg', notes: 'mešana solata' },
    { menuItemName: 'Solata Kraljica', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Solata Kraljica', ingredientId: invTatarskaOmaka.id, quantityPerServing: 1, unit: 'kos', notes: 'tatarska omaka' },
    { menuItemName: 'Cezarjeva solata', ingredientId: invSolata.id, quantityPerServing: 0.2, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Cezarjeva solata', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'piščanec' },
    { menuItemName: 'Cezarjeva solata', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'parmezan' },
    { menuItemName: 'Grška solata', ingredientId: invSolata.id, quantityPerServing: 0.15, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Grška solata', ingredientId: invParadiznik.id, quantityPerServing: 0.1, unit: 'kg', notes: 'paradižnik' },
    { menuItemName: 'Grška solata', ingredientId: invFetaSir.id, quantityPerServing: 0.1, unit: 'kg', notes: 'feta sir' },
    { menuItemName: 'Grška solata', ingredientId: invOlive.id, quantityPerServing: 0.03, unit: 'kg', notes: 'olive' },
    { menuItemName: 'Solata rukola s parmezanom', ingredientId: invRukola.id, quantityPerServing: 1, unit: 'kos', notes: 'rukola' },
    { menuItemName: 'Solata rukola s parmezanom', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'parmezan' },
    { menuItemName: 'Mešana solata s tuno', ingredientId: invSolata.id, quantityPerServing: 0.3, unit: 'kg', notes: 'mešana solata' },
    { menuItemName: 'Mešana solata s tuno', ingredientId: invTunaKos.id, quantityPerServing: 0.15, unit: 'kg', notes: 'tuna' },

    // --- PIZZE ---
    { menuItemName: 'Margerita', ingredientId: invTestoZaPico.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'Margerita', ingredientId: invPelati.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Margerita', ingredientId: invMozzarella.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'Hišna pica', ingredientId: invTestoZaPico.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'Hišna pica', ingredientId: invPelati.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Hišna pica', ingredientId: invMozzarella.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'Hišna pica', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'kuhan pršut' },
    { menuItemName: 'Hišna pica', ingredientId: invDomacaSunka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'domača šunka' },
    { menuItemName: 'Hišna pica', ingredientId: invSuhaSalama.id, quantityPerServing: 0.05, unit: 'kg', notes: 'salama' },
    { menuItemName: 'Hišna pica', ingredientId: invSlanina.id, quantityPerServing: 0.05, unit: 'kg', notes: 'slanina' },
    { menuItemName: 'Hišna pica', ingredientId: invSampinjoni.id, quantityPerServing: 0.05, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'Kraška', ingredientId: invTestoZaPico.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'Kraška', ingredientId: invPelati.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Kraška', ingredientId: invMozzarella.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'Kraška', ingredientId: invPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Kraška', ingredientId: invSampinjoni.id, quantityPerServing: 0.05, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'S tuno', ingredientId: invTestoZaPico.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'S tuno', ingredientId: invPelati.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'S tuno', ingredientId: invMozzarella.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'S tuno', ingredientId: invTunaKos.id, quantityPerServing: 0.1, unit: 'kg', notes: 'tuna' },
    { menuItemName: 'Štirje siri', ingredientId: invTestoZaPico.id, quantityPerServing: 1, unit: 'kg', notes: '1 testo' },
    { menuItemName: 'Štirje siri', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'mozzarella' },
    { menuItemName: 'Štirje siri', ingredientId: invGorgonzola.id, quantityPerServing: 0.05, unit: 'kg', notes: 'gorgonzola' },
    { menuItemName: 'Štirje siri', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'gauda' },
    { menuItemName: 'Štirje siri', ingredientId: invEdamec.id, quantityPerServing: 0.05, unit: 'kg', notes: 'edamec' },

    // --- BURGERJI ---
    { menuItemName: 'Hišni burger', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g goveji patty' },
    { menuItemName: 'Hišni burger', ingredientId: invKozjiSir.id, quantityPerServing: 0.05, unit: 'kg', notes: 'kozji sir' },
    { menuItemName: 'Hišni burger', ingredientId: invSlanina.id, quantityPerServing: 0.05, unit: 'kg', notes: 'slanina' },
    { menuItemName: 'Hišni burger', ingredientId: invCebula.id, quantityPerServing: 0.03, unit: 'kg', notes: 'karamelizirana čebula' },
    { menuItemName: 'The classic', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g goveji patty' },
    { menuItemName: 'The classic', ingredientId: invCheddarSir.id, quantityPerServing: 0.05, unit: 'kg', notes: 'cheddar' },
    { menuItemName: 'The classic', ingredientId: invSolata.id, quantityPerServing: 0.03, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Big BOSS', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g goveji patty' },
    { menuItemName: 'Big BOSS', ingredientId: invRostbeef.id, quantityPerServing: 0.05, unit: 'kg', notes: 'rostbeef' },
    { menuItemName: 'Big BOSS', ingredientId: invTartufi.id, quantityPerServing: 1, unit: 'kos', notes: 'tartufina majoneza' },
    { menuItemName: 'Cheese please', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g goveji patty' },
    { menuItemName: 'Cheese please', ingredientId: invCheddarSir.id, quantityPerServing: 0.05, unit: 'kg', notes: 'cheddar' },
    { menuItemName: 'Green garden', ingredientId: invBurgerPatty.id, quantityPerServing: 1, unit: 'kos', notes: '170g patty' },
    { menuItemName: 'Green garden', ingredientId: invPesto.id, quantityPerServing: 1, unit: 'kos', notes: 'bazilični pesto' },
    { menuItemName: 'Green garden', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Crispy chicken burger', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.18, unit: 'kg', notes: '180g piščančja prsa' },
    { menuItemName: 'Crispy chicken burger', ingredientId: invCheddarSir.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Fit burger', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.18, unit: 'kg', notes: '180g piščančja prsa' },
    { menuItemName: 'Fit burger', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Fit burger', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },

    // --- VEGETARIJANSKE ---
    { menuItemName: 'Zelenjavni zrezki', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Sojini polpeti', ingredientId: invMletnoMeso.id, quantityPerServing: 0.15, unit: 'kg', notes: 'sojini polpeti' },
    { menuItemName: 'Bučke na žaru', ingredientId: invBucke.id, quantityPerServing: 0.25, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Bučke na žaru', ingredientId: invCesen.id, quantityPerServing: 0.01, unit: 'kg', notes: 'česen' },
    { menuItemName: 'Bučke na žaru', ingredientId: invOlivnoOlje.id, quantityPerServing: 0.02, unit: 'L', notes: 'olivno olje' },
    { menuItemName: 'Ocvrte bučke', ingredientId: invBucke.id, quantityPerServing: 0.25, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Ocvrti melancani', ingredientId: invMelancani.id, quantityPerServing: 0.25, unit: 'kg', notes: 'melancani' },
    { menuItemName: 'Vegetarijanska plošča', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Vegetarijanska plošča', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'šampinjoni' },

    // --- PALAČINKE ---
    { menuItemName: 'Hišna sladica', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka' },
    { menuItemName: 'Hišna sladica', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Hišna sladica', ingredientId: invJagodniPire.id, quantityPerServing: 0.05, unit: 'kg', notes: 'jagodni pire' },
    { menuItemName: 'Hišna sladica', ingredientId: invLinoLada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Lino Lada' },
    { menuItemName: 'Hišna sladica', ingredientId: invBelaCokolada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'bela čokolada' },
    { menuItemName: 'Hišna sladica', ingredientId: invPlazmaPiskot.id, quantityPerServing: 0.02, unit: 'kg', notes: 'Plazma biskvit' },
    { menuItemName: 'Raffaello', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka' },
    { menuItemName: 'Raffaello', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Raffaello', ingredientId: invBelaCokolada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'bela čokolada' },
    { menuItemName: 'Raffaello', ingredientId: invLinoLada.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Lino Lada' },
    { menuItemName: 'Raffaello', ingredientId: invMandlji.id, quantityPerServing: 0.02, unit: 'kg', notes: 'mandlji' },
    { menuItemName: 'Raffaello', ingredientId: invKokosovaMoka.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kokosova moka' },
    { menuItemName: 'Raffaello', ingredientId: invRaffaello.id, quantityPerServing: 1, unit: 'kos', notes: 'Raffaello kroglica' },
    { menuItemName: 'Kinder Bueno', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Kinder Bueno', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Kinder Bueno', ingredientId: invKakavZaPalačinke.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kakav' },
    { menuItemName: 'Kinder Bueno', ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čokoladno-lešnikova krema' },
    { menuItemName: 'Kinder Bueno', ingredientId: invKinderBueno.id, quantityPerServing: 1, unit: 'kos', notes: 'Kinder Bueno' },
    { menuItemName: 'Snickers', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Snickers', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Snickers', ingredientId: invKakavZaPalačinke.id, quantityPerServing: 0.02, unit: 'kg', notes: 'kakav' },
    { menuItemName: 'Snickers', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },
    { menuItemName: 'Snickers', ingredientId: invSnickers.id, quantityPerServing: 1, unit: 'kos', notes: 'Snickers' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čokoladno-lešnikova krema' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invMandlji.id, quantityPerServing: 0.02, unit: 'kg', notes: 'lešniki' },
    { menuItemName: 'Ferrero Rocher', ingredientId: invFerreroRocher.id, quantityPerServing: 1, unit: 'kos', notes: 'Ferrero Rocher' },
    { menuItemName: "M&M's", ingredientId: invMokaPalacinke.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moka kakavova' },
    { menuItemName: "M&M's", ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: "M&M's", ingredientId: invNutella.id, quantityPerServing: 0.03, unit: 'kg', notes: 'Nutella' },
    { menuItemName: "M&M's", ingredientId: invMandM.id, quantityPerServing: 0.02, unit: 'kg', notes: "M&M's" },

    // --- OTROŠKE JEDI ---
    { menuItemName: 'Krožnik Miškolin', ingredientId: invGauda.id, quantityPerServing: 0.15, unit: 'kg', notes: 'ocvrti sir' },
    { menuItemName: 'Krožnik Miškolin', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Krožnik Korenjak', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.15, unit: 'kg', notes: 'dunajski zrezek' },
    { menuItemName: 'Krožnik Korenjak', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Otroški pohančki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran/piščanec' },
    { menuItemName: 'Otroški pohančki', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Pizza Malček', ingredientId: invTestoZaPico.id, quantityPerServing: 0.5, unit: 'kg', notes: 'manjše testo' },
    { menuItemName: 'Pizza Malček', ingredientId: invPelati.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Pizza Malček', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'mozzarella' },

    // --- MALICE (Dnevno kosilo) ---
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g zrezek' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Dunajski zrezek', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g zrezek' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Malica - Pariški zrezek', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invRebra.id, quantityPerServing: 0.30, unit: 'kg', notes: '300g rebra' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invKrompir.id, quantityPerServing: 0.25, unit: 'kg', notes: 'pražen krompir' },
    { menuItemName: 'Malica - Pečena rebra', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.25, unit: 'kg', notes: 'piščančje perutničke' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invBBQOmaka.id, quantityPerServing: 0.05, unit: 'L', notes: 'BBQ omaka' },
    { menuItemName: 'Malica - BBQ perutničke', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invSvinjskaPecenko.id, quantityPerServing: 0.30, unit: 'kg', notes: '300g pečenka' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invKrompir.id, quantityPerServing: 0.25, unit: 'kg', notes: 'pražen krompir' },
    { menuItemName: 'Malica - Svinjska pečenka', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invOslic.id, quantityPerServing: 0.20, unit: 'kg', notes: '200g oslič' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Ocvrti oslič', ingredientId: invKrompir.id, quantityPerServing: 0.20, unit: 'kg', notes: 'krompirjeva solata' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invOslic.id, quantityPerServing: 0.15, unit: 'kg', notes: '150g oslič' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invMoka.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paniranje' },
    { menuItemName: 'Malica - Ocvrti oslič s pomfrijem', ingredientId: invPommesFrites.id, quantityPerServing: 0.15, unit: 'kg', notes: 'pomfri' },
    { menuItemName: 'Malica - Ocvrti sir', ingredientId: invGauda.id, quantityPerServing: 0.15, unit: 'kg', notes: 'ocvrti sir' },
    { menuItemName: 'Malica - Ocvrti sir', ingredientId: invSolata.id, quantityPerServing: 0.1, unit: 'kg', notes: 'solata' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invSpageti.id, quantityPerServing: 0.15, unit: 'kg', notes: 'špageti' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invMletnoMeso.id, quantityPerServing: 0.10, unit: 'kg', notes: 'bolognese omaka' },
    { menuItemName: 'Malica - Špageti bolognese', ingredientId: invParadiznik.id, quantityPerServing: 0.05, unit: 'kg', notes: 'paradižnikova omaka' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invMletnoMeso.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mesni sir' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invGauda.id, quantityPerServing: 0.05, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Malica - Mesni sir', ingredientId: invSampinjoni.id, quantityPerServing: 0.03, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Malica - Bograč', ingredientId: invGovedinaBograch.id, quantityPerServing: 0.15, unit: 'kg', notes: 'govedina' },
    { menuItemName: 'Malica - Bograč', ingredientId: invParadiznik.id, quantityPerServing: 0.05, unit: 'kg', notes: 'paradižnik' },
    { menuItemName: 'Malica - Bograč', ingredientId: invCebula.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Malica - Bograč', ingredientId: invPaprika.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paprika' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invGovedinaZaGolaz.id, quantityPerServing: 0.15, unit: 'kg', notes: 'govedina' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invCebula.id, quantityPerServing: 0.03, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Malica - Goveji golaž', ingredientId: invParadiznik.id, quantityPerServing: 0.03, unit: 'kg', notes: 'paradižnikova omaka' },

  ]

  return foodRecipes
}
