// Glavne jedi — Mesne jedi, žar, pečenke

import type { InvItem, RecipeEntry } from '../../types'

export function buildGlavneJedi(inv: Record<string, InvItem>): RecipeEntry[] {
  const {
    invTelecjaPrsa, invKrompir, invMešanaZelenjava,
    invSvinjskaKraca, invSvinjskaPecenko,
    invBeefsteak, invRebra, invBBQOmaka,
    invPrsut, invParmezan,
    invGovedinaBograch, invPaprika, invCebula,
    invGovedinaZaGolaz, invKruhoveRezine,
    invSvinjskiZrezek, invSampinjoni, invSladkaSmetana,
    invKuhanPrsut, invGauda,
    invDomacaSunka, invAnanas,
    invRostbeef, invPiscancjiFile,
    invPiscanecCeli, invPuramjiFile,
    invPecenaKlobasa, invZelje, invKrvavica,
    invPljucnaPecenka,
  } = inv

  return [
    // --- GLAVNE JEDI ---
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invTelecjaPrsa.id, quantityPerServing: 0.3, unit: 'kg', notes: 'telečja prsa' },
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invKrompir.id, quantityPerServing: 0.3, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Polnjena telečja prsa', ingredientId: invMešanaZelenjava.id, quantityPerServing: 0.2, unit: 'kg', notes: 'zelenjava' },
    { menuItemName: 'Pečena svinjska krača', ingredientId: invSvinjskaKraca.id, quantityPerServing: 1, unit: 'kos', notes: '1500g krača' },
    { menuItemName: 'Svinjska pečenka', ingredientId: invSvinjskaPecenko.id, quantityPerServing: 0.45, unit: 'kg', notes: '450g pečenka' },
    { menuItemName: 'Svinjska pečenka', ingredientId: invKrompir.id, quantityPerServing: 0.3, unit: 'kg', notes: 'slan krompir' },
    { menuItemName: 'Telečja pečenka', ingredientId: invTelecjaPrsa.id, quantityPerServing: 0.45, unit: 'kg', notes: '450g telečja' },
    { menuItemName: 'Rumpsteak', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rumpsteak' },
    { menuItemName: 'BBQ rebrca', ingredientId: invRebra.id, quantityPerServing: 0.5, unit: 'kg', notes: '500g rebra' },
    { menuItemName: 'BBQ rebrca', ingredientId: invBBQOmaka.id, quantityPerServing: 1, unit: 'kos', notes: 'BBQ omaka' },
    { menuItemName: 'Beefsteak v poprovi omaki', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g beefsteak' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invBeefsteak.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g beefsteak' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Kraški beefsteak', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invGovedinaBograch.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g govedina' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invPaprika.id, quantityPerServing: 0.1, unit: 'kg', notes: 'paprika' },
    { menuItemName: 'Bograč v kotličku', ingredientId: invCebula.id, quantityPerServing: 0.05, unit: 'kg', notes: 'čebula' },
    { menuItemName: 'Goveji golaž v kotličku', ingredientId: invGovedinaZaGolaz.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g govedina' },
    { menuItemName: 'Goveji golaž v kotličku', ingredientId: invKruhoveRezine.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kruhova rezina' },
    { menuItemName: 'Dunajski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Pariški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'šampinjoni' },
    { menuItemName: 'Hišni zrezek', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'Kraški zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Kraški zrezek', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.05, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Kraški zrezek', ingredientId: invParmezan.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Naravni zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Zrezek z gobami', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Zrezek z gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invDomacaSunka.id, quantityPerServing: 0.05, unit: 'kg', notes: 'šunka' },
    { menuItemName: 'Ljubljanski zrezek', ingredientId: invGauda.id, quantityPerServing: 0.03, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Zrezek v curry omaki', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Sirov zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Sirov zrezek', ingredientId: invGauda.id, quantityPerServing: 0.1, unit: 'kg', notes: 'sir' },
    { menuItemName: 'Hawaii zrezek', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g zrezek' },
    { menuItemName: 'Hawaii zrezek', ingredientId: invAnanas.id, quantityPerServing: 1, unit: 'kos', notes: 'ananas' },
    { menuItemName: 'Tagliata na rukoli', ingredientId: invRostbeef.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rostbeef' },
    { menuItemName: 'Rostbeef', ingredientId: invRostbeef.id, quantityPerServing: 0.25, unit: 'kg', notes: '250g rostbeef' },
    { menuItemName: 'Žar tris', ingredientId: invSvinjskiZrezek.id, quantityPerServing: 0.15, unit: 'kg', notes: 'svinjski kare' },
    { menuItemName: 'Žar tris', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.1, unit: 'kg', notes: 'piščančja prsa' },
    { menuItemName: 'Žar tris', ingredientId: invRostbeef.id, quantityPerServing: 0.1, unit: 'kg', notes: 'rostbeef' },
    { menuItemName: 'Ocvrt pišanec', ingredientId: invPiscanecCeli.id, quantityPerServing: 1, unit: 'kos', notes: 'cel pišanec' },
    { menuItemName: 'Pohančki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.25, unit: 'kg', notes: 'puranji/piščančji' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invPecenaKlobasa.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g pečenica' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invZelje.id, quantityPerServing: 0.15, unit: 'kg', notes: 'zelje' },
    { menuItemName: 'Pečenica s prilogo', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'krompir' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invKrvavica.id, quantityPerServing: 0.3, unit: 'kg', notes: '300g krvavica' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invZelje.id, quantityPerServing: 0.15, unit: 'kg', notes: 'zelje' },
    { menuItemName: 'Krvavica s prilogo', ingredientId: invKrompir.id, quantityPerServing: 0.2, unit: 'kg', notes: 'krompir' },
    { menuItemName: 'S pljučno pečenko in zelenjavo', ingredientId: invPljucnaPecenka.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pljučna pečenka' },
  ]
}
