// Testenine — Špageti, riževi rezanci, Pad Thai

import type { InvItem, RecipeEntry } from '../../types'

export function buildTestenine(inv: Record<string, InvItem>): RecipeEntry[] {
  const {
    invSpageti, invMletnoMeso, invPelati,
    invKuhanPrsut, invSladkaSmetana,
    invSampinjoni, invTartufi,
    invGorgonzola, invPuramjiFile, invCurryPrah,
    invKalamari, invGamberi,
    invPljucnaPecenka, invMozzarella, invMelancani,
    invPiscancjiFile,
    invRizeviRezanci, invBucke, invKorenje, invJajca, invArasidi,
  } = inv

  return [
    // --- TESTENINE ---
    { menuItemName: 'Bolognese', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Bolognese', ingredientId: invMletnoMeso.id, quantityPerServing: 0.15, unit: 'kg', notes: 'mletno meso' },
    { menuItemName: 'Bolognese', ingredientId: invPelati.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Carbonara', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Carbonara', ingredientId: invKuhanPrsut.id, quantityPerServing: 0.1, unit: 'kg', notes: 'pršut' },
    { menuItemName: 'Carbonara', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'Napoli', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Napoli', ingredientId: invPelati.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pelati' },
    { menuItemName: 'Z gobami', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z gobami', ingredientId: invSampinjoni.id, quantityPerServing: 0.15, unit: 'kg', notes: 'gobe' },
    { menuItemName: 'S tartufi', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S tartufi', ingredientId: invTartufi.id, quantityPerServing: 1, unit: 'kos', notes: 'tartufi' },
    { menuItemName: 'S tartufi', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetanova omaka' },
    { menuItemName: 'V gorgonzolini omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'V gorgonzolini omaki', ingredientId: invGorgonzola.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gorgonzola' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran' },
    { menuItemName: 'S puranom v smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invPuramjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'puran' },
    { menuItemName: 'S puranom v curry omaki', ingredientId: invCurryPrah.id, quantityPerServing: 1, unit: 'kos', notes: 'curry' },
    { menuItemName: 'V smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'V smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invKalamari.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kalamari' },
    { menuItemName: 'Z morskimi sadeži', ingredientId: invGamberi.id, quantityPerServing: 0.1, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invKalamari.id, quantityPerServing: 0.1, unit: 'kg', notes: 'kalamari' },
    { menuItemName: 'Z morskimi sadeži v smetanovi omaki', ingredientId: invSladkaSmetana.id, quantityPerServing: 1, unit: 'kos', notes: 'smetana' },
    { menuItemName: 'S pljučno pečenko in zelenjavo', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S pljučno pečenko in zelenjavo', ingredientId: invPljucnaPecenka.id, quantityPerServing: 0.2, unit: 'kg', notes: 'pljučna pečenka' },
    { menuItemName: 'Sicilijana', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Sicilijana', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moccarela' },
    { menuItemName: 'Sicilijana', ingredientId: invMelancani.id, quantityPerServing: 0.1, unit: 'kg', notes: 'melancani' },
    { menuItemName: 'Z gamberi na rdeče ali belo', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'Z gamberi na rdeče ali belo', ingredientId: invGamberi.id, quantityPerServing: 0.15, unit: 'kg', notes: 'gamberi' },
    { menuItemName: 'S piščancem', ingredientId: invSpageti.id, quantityPerServing: 0.2, unit: 'kg', notes: '200g testenine' },
    { menuItemName: 'S piščancem', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'piščanec' },
    { menuItemName: 'S piščancem', ingredientId: invMozzarella.id, quantityPerServing: 0.1, unit: 'kg', notes: 'moccarela' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invRizeviRezanci.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riževi rezanci' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invKorenje.id, quantityPerServing: 0.05, unit: 'kg', notes: 'korenje' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Pad Thai z zelenjavo', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invRizeviRezanci.id, quantityPerServing: 0.2, unit: 'kg', notes: 'riževi rezanci' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invPiscancjiFile.id, quantityPerServing: 0.15, unit: 'kg', notes: 'piščanec' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invBucke.id, quantityPerServing: 0.05, unit: 'kg', notes: 'bučke' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invJajca.id, quantityPerServing: 1, unit: 'kos', notes: '1 jajce' },
    { menuItemName: 'Pad Thai s piščancem', ingredientId: invArasidi.id, quantityPerServing: 0.03, unit: 'kg', notes: 'arašidi' },
  ]
}
